-- Batch 4 customers: 62
CREATE TABLE IF NOT EXISTS woo_migration_map (entity_type TEXT NOT NULL, woo_id TEXT NOT NULL, new_id UUID NOT NULL, UNIQUE(entity_type, woo_id));

INSERT INTO customers (company_name, contact_person, email, phone, billing_street, billing_city, billing_postal_code, billing_country, shipping_street, shipping_city, shipping_postal_code, shipping_country, shipping_same_as_billing)
VALUES
('Pizza Aro', 'Pizza Aro', 'woo4-1@import.local', NULL, 'Wattstraat 7A', 'Zoetermeer', '2723 PZ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bakkerij de Hazelaar', 'Bakkerij de Hazelaar', 'woo4-2@import.local', NULL, 'Hazelaarstraat 10', 'Woerden', '3442 EN', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('De Luifelbaan', 'De Luifelbaan', 'woo4-3@import.local', NULL, 'Vijf Meiplein', 'Leiden', '2321 TC', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('MD Food', 'MD Food', 'woo4-4@import.local', NULL, 'Petuniatuin 8', 'Zoetermeer', '2724 NA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Nur Bakkerij', 'Nur Bakkerij', 'woo4-5@import.local', NULL, 'Haarlemmerstraat 259', 'Leiden', '2312 DT', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Alesta Food', 'Alesta Food', 'woo4-6@import.local', NULL, 'Ambachtsherenpad 12, 2722 BS Zoetermeer', 'Zoetermeer', '2722 BS', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Saray PideHuis', 'Saray PideHuis', 'woo4-7@import.local', NULL, 'Steenstraat 20', 'Leiden', '2312 BW', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Indoor SpeelParadijs ZuiderPark', 'Indoor SpeelParadijs ZuiderPark', 'woo4-8@import.local', NULL, 'Mr. P. Droogleever Fortuynweg 79', 'Den Haag', '2533SP', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizzeria & Dönerhuis De Gaarde', 'Pizzeria & Dönerhuis De Gaarde', 'woo4-9@import.local', NULL, 'Vrederustlaan 123', 'Den Haag', '2543 SM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Babas Restaurant', 'Babas Restaurant', 'woo4-10@import.local', NULL, 'Heeswijkplein 18', 'Den Haag', '2531 HC', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('AG Emmoglu Supermarkt', 'AG Emmoglu Supermarkt', 'woo4-11@import.local', NULL, 'Brandtstraat 1', 'Den Haag', '2572CA Den Haag', 'NL', 'Brandtstraat 1', 'Den Haag', '2572CA Den Haag', 'NL', TRUE),
('Sultan Ahmet BV', 'Sultan Ahmet BV', 'woo4-12@import.local', NULL, 'Watermolen 6', 'Leiden', '2317 ST', 'NL', 'Watermolen 6', 'Leiden', '2317 ST', 'NL', TRUE),
('De Serar''s', 'De Serar''s', 'woo4-13@import.local', NULL, 'De Stede 21', 'Den Haag', '2543 BG', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Eetcafe Elif', 'Eetcafe Elif', 'woo4-14@import.local', NULL, 'Dedemsvaartweg', 'Den Haag', '2545 AX', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('YAREN PIZZA EN DONER', 'YAREN PIZZA EN DONER', 'woo4-15@import.local', NULL, 'Geuzenplein 17', 'Schiedam', '3123CK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Dicle', 'Dicle', 'woo4-16@import.local', NULL, 'Kempstraat 17', 'Den Haag', '2572 GA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Jacks corner', 'Jacks corner', 'woo4-17@import.local', NULL, 'Leemansplein 544', 'Den Haag', '2521 EJ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Buurtwinkel Stipt', 'Buurtwinkel Stipt', 'woo4-18@import.local', NULL, 'Van Zeggelenlaan 240', 'Den Haag', '2524AZ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Rania', 'Rania', 'woo4-19@import.local', NULL, 'Winkelhof 5', 'Leiderdorp', '2353 EH', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Ak-Al Bakkerij Herenstraat', 'Ak-Al Bakkerij Herenstraat', 'woo4-20@import.local', NULL, 'Herenstraat 4', 'Leiden', '2313 AK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('San Marina', 'San Marina', 'woo4-21@import.local', NULL, 'Gerrit Achterberghove', 'Zoetermeer', '2717 XZ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('De Rotonde Kebab', 'De Rotonde Kebab', 'woo4-22@import.local', NULL, 'Slotermeerlaan 3', 'Amsterdam', '1064GX', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Dream Kebab Katwijk', 'Dream Kebab Katwijk', 'woo4-23@import.local', NULL, 'Taatedam 2', 'Katwijk aan zee', '2225 BN', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Dream Kebab Noordwijkerhout', 'Dream Kebab Noordwijkerhout', 'woo4-24@import.local', NULL, 'Zeestraat 4', 'Noordwijkerhout', '2211 XG', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Dream Kebab Voorhout', 'Dream Kebab Voorhout', 'woo4-25@import.local', NULL, 'Herenstraat 88A', 'Voorhout', '2215KK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bakkerij Hesse Place', 'Bakkerij Hesse Place', 'woo4-26@import.local', NULL, 'Hesseplaats 71', 'Rotterdam', '3069EA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('EetCafe De haven', 'EetCafe De haven', 'woo4-27@import.local', NULL, 'Calandakade 170', 'Den Haag', '2521AA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('HerenHofEethuis', 'HerenHofEethuis', 'woo4-28@import.local', NULL, 'HerenHof 287', 'Alpen aan den Rijn', '2402DL', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Eethuis Hoofstraat', 'Eethuis Hoofstraat', 'woo4-29@import.local', NULL, 'Hooftstraat 78', 'Alphen aan den Rijn', '2406 GL', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Sohbet', 'Sohbet', 'woo4-30@import.local', NULL, 'Calandkade 168', 'Den Haag', '2521AA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Supermarkt Houtwijk', 'Supermarkt Houtwijk', 'woo4-31@import.local', NULL, 'Hildo kroplaan 96', 'Den Haag', '2552 XT', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Massada Roelofarendsveen', 'Massada Roelofarendsveen', 'woo4-32@import.local', NULL, 'Noordplein 3', 'Roelofarendsveen', '2371 DA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Oranje Oosterheem', 'Oranje Oosterheem', 'woo4-33@import.local', NULL, 'Westerschelde 364', 'Zoetermeer', '2721 NN', 'NL', 'Westerschelde 364', 'Zoetermeer', '2721 NN', 'NL', TRUE),
('Lekker Jammie', 'Lekker Jammie', 'woo4-34@import.local', NULL, 'Hoge Rijndijk 98', 'Leiden', '2313 KM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Mirom supermarkt', 'Mirom supermarkt', 'woo4-35@import.local', NULL, 'Spinozaweg 407', 'Rotterdam', '3076 ET', 'NL', 'Spinozaweg 407', 'Rotterdam', '3076 ET', 'NL', TRUE),
('Hoornes Supermarkt en Bakkerij', 'Hoornes Supermarkt en Bakkerij', 'woo4-36@import.local', NULL, 'Hoorneslaan 329', 'Katwijk aan Zee', '2221 GA', 'NL', 'Hoorneslaan 329', 'Katwijk aan Zee', '2221 GA', 'NL', TRUE),
('Seda Bakkerij', 'Seda Bakkerij', 'woo4-37@import.local', NULL, 'Leyweg 1170', 'Den Haag', '2545 HH', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Yahya VOF', 'Yahya VOF', 'woo4-38@import.local', NULL, 'Paul Krugerlaan 36 -40', 'Den Haag', '2571 HK', 'NL', 'Paul Krugerlaan 36 -40', 'Den Haag', '2571 HK', 'NL', TRUE),
('Snackbar Onder Den Toren', 'Snackbar Onder Den Toren', 'woo4-39@import.local', NULL, 'Voorstraat 3', 'Wijk aan Zee', '1949 BG', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('ZAM ZAM XL', 'ZAM ZAM XL', 'woo4-40@import.local', NULL, 'Raamsteeg 73', 'Leiden', '2311 PM', 'NL', 'Raamsteeg 73', 'Leiden', '2311 PM', 'NL', TRUE),
('AKK Doner Haarlem', 'AKK Doner Haarlem', 'woo4-41@import.local', NULL, 'Kruisweg 48', 'Haarlem', '2011LD', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Ramsis', 'Ramsis', 'woo4-42@import.local', NULL, 'Schoolstraat 30', 'Den Haag', '2511 AX', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('HerenHof Eethuis', 'HerenHof Eethuis', 'woo4-43@import.local', NULL, 'HerenHof 287', 'Alpen aan den Rijn', '2402DL', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Yeyen Supermarkt', 'Yeyen Supermarkt', 'woo4-44@import.local', NULL, 'Escamplaan 305', 'Den Haag', '2547 EA', 'NL', 'Escamplaan 305', 'Den Haag', '2547 EA', 'NL', TRUE),
('Pizza Express', 'Pizza Express', 'woo4-45@import.local', NULL, 'Schoolstraat 103', 'Voorschoten', '2251 BG', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizzeria Roomburg', 'Pizzeria Roomburg', 'woo4-46@import.local', NULL, 'IJsselkade 43', 'Leiden', '2314VM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Serdar Supermarkt', 'Serdar Supermarkt', 'woo4-47@import.local', NULL, 'Rijksstraatweg 46', 'Hellevoetsluis', '3223 KA', 'NL', 'Rijksstraatweg 46', 'Hellevoetsluis', '3223 KA', 'NL', TRUE),
('Orange Food Group B.V.', NULL, 'woo4-48@import.local', NULL, 'Doctor Wiardi Beckmansingel 13', 'Vlaardingen', '3132CL', 'NL', 'Doctor Wiardi Beckmansingel 13', 'Vlaardingen', '3132CL', 'NL', TRUE),
('Can Market', 'Can Market', 'woo4-49@import.local', NULL, 'Kon. Wilhelminalaan 68-70', 'Gorinchem', '4205 EZ', 'NL', 'Kon. Wilhelminalaan 68-70', 'Gorinchem', '4205 EZ', 'NL', TRUE),
('Sultan Pizzeria', 'Sultan Pizzeria', 'woo4-50@import.local', NULL, 'De Markt 325', 'Krimpen aan de Lek', '2931 EC', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Snackbar Stevenshof', 'Snackbar Stevenshof', 'woo4-51@import.local', NULL, 'Stevensbloem 5', 'Leiden', '2331 JA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Slagerij Atas', 'Slagerij Atas', 'woo4-52@import.local', NULL, 'Pr. Irenelaan 96', 'Alphen aan den Rijn', '2404 BJ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('De Gouwe auto & banden', 'De Gouwe auto & banden', 'woo4-53@import.local', NULL, 'Noordkade 76', 'Waddinxveen', '2741 EZ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('alternatief23 B.V', 'alternatief23 B.V', 'woo4-54@import.local', NULL, 'Zuiderkruis 179', 'Veenendaal', '3902WG', 'NL', 'Zuiderkruis 179', 'Veenendaal', '3902WG', 'NL', TRUE),
('JINGDONG RETAIL (NETHERLANDS) B.V.', 'JINGDONG RETAIL (NETHERLANDS) B.V.', 'woo4-55@import.local', NULL, 'Da Vincistraat 5', 'Berkel en Rodenrijs', '2652 XE', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Desginverenda', 'Desginverenda', 'woo4-56@import.local', NULL, 'Jacob schorerlaan 41', 'Den haag', '2525ZP', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Baran Broodjeszaak', 'Baran Broodjeszaak', 'woo4-57@import.local', NULL, 'Hoefkade 1244', 'Den Haag', '2525 HK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('EKO Supermarkt', 'EKO Supermarkt', 'woo4-58@import.local', NULL, 'Kempstraat 122', 'Den Haag', '2572 GK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Tasty Point', 'Tasty Point', 'woo4-59@import.local', NULL, 'Voldersgracht 42', 'Den Haag', '2512JV', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizzeria La Dolce Vita', 'Pizzeria La Dolce Vita', 'woo4-60@import.local', NULL, 'Rembrandtlaan 52', 'Voorburg', '2271 GK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('OBS Kwintijn', 'OBS Kwintijn', 'woo4-61@import.local', NULL, 'Broekplein 5', 'Leiden', '2318 TJ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Supermarkt Joud', 'Supermarkt Joud', 'woo4-62@import.local', NULL, 'Venneperstraat 12', 'Nieuw-Vennep', '2151 AR', 'NL', 'Venneperstraat 12', 'Nieuw-Vennep', '2151 AR', 'NL', TRUE);

-- Map by email pattern woo4-*
INSERT INTO woo_migration_map (entity_type, woo_id, new_id)
SELECT 'customer', company_name, id FROM customers WHERE email LIKE 'woo4-%@import.local'
ON CONFLICT (entity_type, woo_id) DO NOTHING;

SELECT (SELECT COUNT(*) FROM woo_migration_map WHERE entity_type = 'customer') as mapped;