-- Batch 15 customers: 97
CREATE TABLE IF NOT EXISTS woo_migration_map (entity_type TEXT NOT NULL, woo_id TEXT NOT NULL, new_id UUID NOT NULL, UNIQUE(entity_type, woo_id));

INSERT INTO customers (company_name, contact_person, email, phone, billing_street, billing_city, billing_postal_code, billing_country, shipping_street, shipping_city, shipping_postal_code, shipping_country, shipping_same_as_billing)
VALUES
('Meze Food', 'Meze Food', 'woo15-1@import.local', NULL, 'Rue de la gaite 105', 'Anderlecht', '1070', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Yeni Bahar BV', 'Yeni Bahar BV', 'woo15-2@import.local', NULL, 'Oostermeent noord 56', 'Huizen', '1274SC', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Simit Paleis A.S.', 'Simit Paleis A.S.', 'woo15-3@import.local', NULL, 'Postjesweg 105', 'Amsterdam', '1057 DZ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Broodjeszaak de Mix', 'Broodjeszaak de Mix', 'woo15-4@import.local', NULL, 'Kostmand 18a', 'Huizen', '1276 CJ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('The Address Cafe Restaurant', 'The Address Cafe Restaurant', 'woo15-5@import.local', NULL, 'Slotermeerlaan 111', 'Amsterdam', '1063 JN', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Ekmek Teknesi', 'Ekmek Teknesi', 'woo15-6@import.local', NULL, 'Burgemeester van Leeuwenlaan 77', 'Amsterdam', '1064 KM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('De Rotonde Kebab', 'De Rotonde Kebab', 'woo15-7@import.local', NULL, 'Slotermeerlaan 3', 'Amsterdam', '1064GX', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Ak-Al Bakkerij Herenstraat', 'Ak-Al Bakkerij Herenstraat', 'woo15-8@import.local', NULL, 'Herenstraat 4', 'Leiden', '2313 AK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Dream Kebab Voorhout', 'Dream Kebab Voorhout', 'woo15-9@import.local', NULL, 'Herenstraat 88A', 'Voorhout', '2215KK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Dream Kebab Katwijk', 'Dream Kebab Katwijk', 'woo15-10@import.local', NULL, 'Taatedam 2', 'Katwijk aan zee', '2225 BN', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Dream Kebab Noordwijkerhout', 'Dream Kebab Noordwijkerhout', 'woo15-11@import.local', NULL, 'Zeestraat 4', 'Noordwijkerhout', '2211 XG', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Snackbar te britten', 'Snackbar te britten', 'woo15-12@import.local', NULL, 'Zwaaikom 7', 'Katwijk aan Zee', '2225 HX', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Seda Bakkerij', 'Seda Bakkerij', 'woo15-13@import.local', NULL, 'Leyweg 1170', 'Den Haag', '2545 HH', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Gulcan Bakkerij', 'Gulcan Bakkerij', 'woo15-14@import.local', NULL, 'Morsweg 23', 'Leiden', '2312 AS', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Yahya VOF', 'Yahya VOF', 'woo15-15@import.local', NULL, 'Paul Krugerlaan 36 -40', 'Den Haag', '2571 HK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Jacks corner', 'Jacks corner', 'woo15-16@import.local', NULL, 'Leemansplein 544', 'Den Haag', '2521 EJ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Saray PideHuis', 'Saray PideHuis', 'woo15-17@import.local', NULL, 'Steenstraat 20', 'Leiden', '2312 BW', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Oranje Snacks', 'Oranje Snacks', 'woo15-18@import.local', NULL, 'Theresiastraat 34', 'Den Haag', '2593 AP', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizza Bella Maria', 'Pizza Bella Maria', 'woo15-19@import.local', NULL, 'Van Zeggelenlaan 81', 'Den Haag', '2524 AC', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Tasty Corner Delft', 'Tasty Corner Delft', 'woo15-20@import.local', NULL, 'Zuidwal 47', 'Delft', '2611 DD', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('La Casa Doner', 'La Casa Doner', 'woo15-21@import.local', NULL, 'Weimarstraat 343', 'Den Haag', '2562 HK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Snackbar De Joker Pizzeria Grillroom', 'Snackbar De Joker Pizzeria Grillroom', 'woo15-22@import.local', NULL, 'Bergweg 160-A', 'Rotterdam', '3036 BK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizza Pizza', 'Pizza Pizza', 'woo15-23@import.local', NULL, 'Erasmusweg 2', 'Den Haag', '2532 CP', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Durum Evi', 'Durum Evi', 'woo15-24@import.local', NULL, 'Paul Krugerplein 7', 'Den Haag', '2571 HT', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Maxima 4', 'Maxima 4', 'woo15-25@import.local', NULL, 'Spinozaweg 399', 'Rotterdam', '3076 CB', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Food Staion', 'Food Staion', 'woo15-26@import.local', NULL, 'Stieltjesweg 232', 'Delft', '2628 CK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bella Ay Pizza & Döner Huis', 'Bella Ay Pizza & Döner Huis', 'woo15-27@import.local', NULL, 'Dijkstraat 37', 'Honselersdijk', '2675 AV', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Aya hicret', 'Aya hicret', 'woo15-28@import.local', NULL, 'Lange Kerkstraat 35/A', 'Schiedam', '3111 NN', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bakkerij Hesse Place', 'Bakkerij Hesse Place', 'woo15-29@import.local', NULL, 'Hesseplaats 71', 'Rotterdam', '3069EA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizzeria & Dönerhuis De Gaarde', 'Pizzeria & Dönerhuis De Gaarde', 'woo15-30@import.local', NULL, 'Vrederustlaan 123', 'Den Haag', '2543 SM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Fastfood Ramak', 'Fastfood Ramak', 'woo15-31@import.local', NULL, 'Oude Kustlijn 106', 'Den Haag', '2496 SH', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Mirom supermarkt', 'Mirom supermarkt', 'woo15-32@import.local', NULL, NULL, 'Rotterdam', '3076 ET', 'NL', NULL, 'Rotterdam', '3076 ET', 'NL', TRUE),
('JAF EN SLAGERIJ EN TOKO', 'JAF EN SLAGERIJ EN TOKO', 'woo15-33@import.local', NULL, 'Raadhuisplein 131', 'Krimpen aan den IJssel', '2922AL', 'NL', 'Raadhuisplein 131', 'Krimpen aan den IJssel', '2922AL', 'NL', TRUE),
('Alfa Supermarkt', 'Alfa Supermarkt', 'woo15-34@import.local', NULL, 'Mercatorweg 11-19', 'Hoek van Holland', '3151 CJ', 'NL', 'Mercatorweg 11-19', 'Hoek van Holland', '3151 CJ', 'NL', TRUE),
('Sohbet', 'Sohbet', 'woo15-35@import.local', NULL, 'Calandkade 168', 'Den Haag', '2521AA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Sohbet BBQ cafe restaurant', 'Sohbet BBQ cafe restaurant', 'woo15-36@import.local', NULL, 'Middellaan 5', 'Velp', '6288 RP', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Tasty Point', 'Tasty Point', 'woo15-37@import.local', NULL, 'Voldersgracht 42', 'Den Haag', '2512JV', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizza Spidi', 'Pizza Spidi', 'woo15-38@import.local', NULL, 'Van Nesstraat 31', 'Alphen aan den Rijn', '2404 AV', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Groen76', 'Groen76', 'woo15-39@import.local', NULL, 'Stevinstraat 159', 'Den Haag', '2587 EE', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('HerenHof Eethuis', 'HerenHof Eethuis', 'woo15-40@import.local', NULL, 'HerenHof 287', 'Alpen aan den Rijn', '2402DL', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Eethuis Hoofstraat', 'Eethuis Hoofstraat', 'woo15-41@import.local', NULL, 'Hooftstraat 78', 'Alphen aan den Rijn', '2406 GL', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Adam Broodjeszaak', 'Adam Broodjeszaak', 'woo15-42@import.local', NULL, 'Hoefkade 796', 'Den Haag', '2526 CT', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bakkerij Driebergen', 'Bakkerij Driebergen', 'woo15-43@import.local', NULL, 'Driebergenstraat 337', 'Den Haag', '2546 BK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('EetCafe De haven', 'EetCafe De haven', 'woo15-44@import.local', NULL, 'Calandakade 170', 'Den Haag', '2521AA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Ramsis', 'Ramsis', 'woo15-45@import.local', NULL, 'Schoolstraat 30', 'Den Haag', '2511 AX', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bakkerij Bahar Nur', 'Bakkerij Bahar Nur', 'woo15-46@import.local', NULL, 'Dierenselaan 127', 'Den Haag', '2573XS', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Slagerij Atas', 'Slagerij Atas', 'woo15-47@import.local', NULL, 'Pr. Irenelaan 96', 'Alphen aan den Rijn', '2404 BJ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Nemrut Doner Kebab', 'Nemrut Doner Kebab', 'woo15-48@import.local', NULL, 'Leusderweg 64', 'Amersfoort', '3817KB', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Arya Eethuis Leiden', 'Arya Eethuis Leiden', 'woo15-49@import.local', NULL, 'Standerdmolen 19', 'Leiden', '2317 NZ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('San Marina', 'San Marina', 'woo15-50@import.local', NULL, 'Gerrit Achterberghove', 'Zoetermeer', '2717 XZ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bakkerij Nasib', 'Bakkerij Nasib', 'woo15-51@import.local', NULL, 'Weidstraat 11', 'IJsselstein', '3401 DL', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Aps Burger', 'Aps Burger', 'woo15-52@import.local', NULL, 'Bevrijdingsplein 43', 'Leiden', '2321 DX', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Seryana', 'Seryana', 'woo15-53@import.local', NULL, 'Hoogstraat 3', 'Gouda', '2801 HG', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Elif Bakkerij', 'Elif Bakkerij', 'woo15-54@import.local', NULL, 'Kentgensplein 13', 'Zoetermeer', '2717 HS', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Karadag Food', 'Karadag Food', 'woo15-55@import.local', NULL, 'Meeuwenveld 16', 'Zoetermeer', '2727 AK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Alesta Food', 'Alesta Food', 'woo15-56@import.local', NULL, 'Ambachtsherenpad 12, 2722 BS Zoetermeer', 'Zoetermeer', '2722 BS', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bakkerij Çiçek', 'Bakkerij Çiçek', 'woo15-57@import.local', NULL, 'Middelwaard 62', 'Zoetermeer', '2716 CW', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Eethuis Ak-AL', 'Eethuis Ak-AL', 'woo15-58@import.local', NULL, 'Stationsweg 18', 'Leiden', '2312 AV', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('De Luifelbaan', 'De Luifelbaan', 'woo15-59@import.local', NULL, 'Vijf Meiplein', 'Leiden', '2321 TC', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizza Express', 'Pizza Express', 'woo15-60@import.local', NULL, 'Schoolstraat 103', 'Voorschoten', '2251 BG', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bakkerij de Hazelaar', 'Bakkerij de Hazelaar', 'woo15-61@import.local', NULL, 'Hazelaarstraat 10', 'Woerden', '3442 EN', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizza Aro', 'Pizza Aro', 'woo15-62@import.local', NULL, 'Wattstraat 7A', 'Zoetermeer', '2723 PZ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Ak-Al Bakkerij', 'Ak-Al Bakkerij', 'woo15-63@import.local', NULL, 'Sumatrastraat 155', 'Leiden', '2315 BC', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Oranje Oosterheem', 'Oranje Oosterheem', 'woo15-64@import.local', NULL, 'Westerschelde 364', 'Zoetermeer', '2721 NN', 'NL', 'Westerschelde 364', 'Zoetermeer', '2721 NN', 'NL', TRUE),
('ZAM ZAM XL', 'ZAM ZAM XL', 'woo15-65@import.local', NULL, 'Raamsteeg 73', 'Leiden', '2311 PM', 'NL', 'Raamsteeg 73', 'Leiden', '2311 PM', 'NL', TRUE),
('Sultan Ahmet BV', 'Sultan Ahmet BV', 'woo15-66@import.local', NULL, 'Watermolen 6', 'Leiden', '2317 ST', 'NL', 'Watermolen 6', 'Leiden', '2317 ST', 'NL', TRUE),
('De Serar''s', 'De Serar''s', 'woo15-67@import.local', NULL, 'De Stede 21', 'Den Haag', '2543 BG', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Emigro B.V', 'Emigro B.V', 'woo15-68@import.local', NULL, 'Van der Kunstraat 30/32', 'Den Haag', '2521 BC', 'NL', 'Van der Kunstraat 30/32', 'Den Haag', '2521 BC', 'NL', TRUE),
('Orange Food Group B.V.', 'Orange Food', 'woo15-69@import.local', NULL, 'Doctor Wiardi Beckmansingel 13', 'Vlaardingen', '3132CL', 'NL', 'Doctor Wiardi Beckmansingel 13', 'Vlaardingen', '3132CL', 'NL', TRUE),
('Hoornes Supermarkt en Bakkerij', 'Hoornes Supermarkt en Bakkerij', 'woo15-70@import.local', NULL, 'Hoorneslaan 329', 'Katwijk aan Zee', '2221 GA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Serdar Supermarkt', 'Serdar Supermarkt', 'woo15-71@import.local', NULL, 'Rijksstraatweg 46', 'Hellevoetsluis', '3223 KA', 'NL', 'Rijksstraatweg 46', 'Hellevoetsluis', '3223 KA', 'NL', TRUE),
('Can Market', 'Can Market', 'woo15-72@import.local', NULL, 'Kon. Wilhelminalaan 68-70', 'Gorinchem', '4205 EZ', 'NL', 'Kon. Wilhelminalaan 68-70', 'Gorinchem', '4205 EZ', 'NL', TRUE),
('Rania', 'Rania', 'woo15-73@import.local', NULL, 'Winkelhof 5', 'Leiderdorp', '2353 EH', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Snackbar Onder Den Toren', 'Snackbar Onder Den Toren', 'woo15-74@import.local', NULL, 'Voorstraat 3', 'Wijk aan Zee', '1949 BG', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Eetcafe Elif', 'Eetcafe Elif', 'woo15-75@import.local', NULL, 'Dedemsvaartweg', 'Den Haag', '2545 AX', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Nur Bakkerij', 'Nur Bakkerij', 'woo15-76@import.local', NULL, 'Haarlemmerstraat 259', 'Leiden', '2312 DT', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Luiten Food', 'Luiten Food', 'woo15-77@import.local', '0031 71 580 8020', 'Klaverblad 11', 'Leidschendam', '2266 JK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Ons Bakkertje de veen', 'Ons Bakkertje de veen', 'woo15-78@import.local', NULL, 'Noordeinde 13', 'Roelofarendsveen', '2371CM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Baronie Doner Place', 'Baronie Doner Place', 'woo15-79@import.local', NULL, 'Baronie 100', 'Alphen aan den Rijn', '2404 XH', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Massada Roelofarendsveen', 'Massada Roelofarendsveen', 'woo15-80@import.local', NULL, 'Noordplein 3', 'Roelofarendsveen', '2371 DA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Indoor SpeelParadijs ZuiderPark', 'Indoor SpeelParadijs ZuiderPark', 'woo15-81@import.local', NULL, 'Mr. P. Droogleever Fortuynweg 79', 'Den Haag', '2533SP', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Gunaydin Sulu Yemek Restaurant', 'Gunaydin Sulu Yemek Restaurant', 'woo15-82@import.local', NULL, 'Gedempte Gracht 405', 'Den Haag', '2512 AM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizzeria La Dolce Vita', 'Pizzeria La Dolce Vita', 'woo15-83@import.local', NULL, 'Rembrandtlaan 52', 'Voorburg', '2271 GK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Yeyen', 'Yeyen', 'woo15-84@import.local', NULL, NULL, 'Den Haag', '2547 EA', 'NL', NULL, 'Den Haag', '2547 EA', 'NL', TRUE),
('EKO Supermarkt', 'EKO Supermarkt', 'woo15-85@import.local', NULL, 'Kempstraat 122', 'Den Haag', '2572 GK', 'NL', 'Kempstraat 122', 'Den Haag', '2572 GK', 'NL', TRUE),
('ABM RESTYLING', 'ABM RESTYLING', 'woo15-86@import.local', NULL, NULL, NULL, NULL, 'NL', 'Clara Wieckpad 5', 'Leiden', '2324 DV', 'NL', FALSE),
('Lekkerland Nederland B.V.', 'Lekkerland Nederland B.V.', 'woo15-87@import.local', NULL, 'Ekkersrijt 7601', 'Son en Breugel', '5692 HR', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Aktas Supermarkt & Bakkerij', 'Aktas Supermarkt & Bakkerij', 'woo15-88@import.local', NULL, 'Jan van der Heijdenstraat 115', 'Den Haag', '2522 EM', 'NL', 'Jan van der Heijdenstraat 115', 'Den Haag', '2522 EM', 'NL', TRUE),
('AG Emmoglu Supermarkt', 'AG Emmoglu Supermarkt', 'woo15-89@import.local', NULL, 'Brandtstraat 1', 'Den Haag', '2572CA Den Haag', 'NL', 'Brandtstraat 1', 'Den Haag', '2572CA Den Haag', 'NL', TRUE),
('Supermarkt Houtwijk', 'Supermarkt Houtwijk', 'woo15-90@import.local', NULL, NULL, 'Den Haag', '2552 XT', 'NL', NULL, 'Den Haag', '2552 XT', 'NL', TRUE),
('01Grill', '01Grill', 'woo15-91@import.local', NULL, 'Henri Dunantlaan 82', 'Rijswijk', '2286 GE', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Snackbar Stevenshof', 'Snackbar Stevenshof', 'woo15-92@import.local', NULL, 'Stevensbloem 5', 'Leiden', '2331 JA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Birlik B.V.', 'Birlik B.V.', 'woo15-93@import.local', NULL, 'Zuiderkruis 179', 'Veenendaal', '3902 WG', 'NL', 'Zuiderkruis 179', 'Veenendaal', '3902 WG', 'NL', TRUE),
('Best Doner Snacks B.V.', 'Best Doner Snacks B.V.', 'woo15-94@import.local', NULL, 'Jan Pieter Heijestraat 125', 'Amsterdam', '1054ME', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Basak Bakery', 'Basak Bakery', 'woo15-95@import.local', NULL, 'Prins Hendrikstraat 32a', 'Den Haag', '2518 HT', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Slagerij Ramak Ypenburg', 'Slagerij Ramak Ypenburg', 'woo15-96@import.local', NULL, 'Oude Kustlijn 115', 'Den Haag', '2496SK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Yeyen Supermarkt', 'Yeyen Supermarkt', 'woo15-97@import.local', NULL, 'Escamplaan 305', 'Den Haag', '2547 EA', 'NL', 'Escamplaan 305', 'Den Haag', '2547 EA', 'NL', TRUE);

-- Map by email pattern woo15-*
INSERT INTO woo_migration_map (entity_type, woo_id, new_id)
SELECT 'customer', company_name, id FROM customers WHERE email LIKE 'woo15-%@import.local'
ON CONFLICT (entity_type, woo_id) DO NOTHING;

SELECT (SELECT COUNT(*) FROM woo_migration_map WHERE entity_type = 'customer') as mapped;