-- Batch 9 customers: 87
CREATE TABLE IF NOT EXISTS woo_migration_map (entity_type TEXT NOT NULL, woo_id TEXT NOT NULL, new_id UUID NOT NULL, UNIQUE(entity_type, woo_id));

INSERT INTO customers (company_name, contact_person, email, phone, billing_street, billing_city, billing_postal_code, billing_country, shipping_street, shipping_city, shipping_postal_code, shipping_country, shipping_same_as_billing)
VALUES
('Pizzeria & Dönerhuis De Gaarde', 'Pizzeria & Dönerhuis De Gaarde', 'woo9-1@import.local', NULL, 'Vrederustlaan 123', 'Den Haag', '2543 SM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Jacks corner', 'Jacks corner', 'woo9-2@import.local', NULL, 'Leemansplein 544', 'Den Haag', '2521 EJ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Seda Bakkerij', 'Seda Bakkerij', 'woo9-3@import.local', NULL, 'Leyweg 1170', 'Den Haag', '2545 HH', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Adam Broodjeszaak', 'Adam Broodjeszaak', 'woo9-4@import.local', NULL, 'Hoefkade 796', 'Den Haag', '2526 CT', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bakkerij Driebergen', 'Bakkerij Driebergen', 'woo9-5@import.local', NULL, 'Driebergenstraat 337', 'Den Haag', '2546 BK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Star Eethuis', 'Star Eethuis', 'woo9-6@import.local', NULL, 'Jaap Hoekdreef 20', 'Den Haag', '2492 JS', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Indoor SpeelParadijs ZuiderPark', 'Indoor SpeelParadijs ZuiderPark', 'woo9-7@import.local', NULL, 'Mr. P. Droogleever Fortuynweg 79', 'Den Haag', '2533SP', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('HerenHof Eethuis', 'HerenHof Eethuis', 'woo9-8@import.local', NULL, 'HerenHof 287', 'Alpen aan den Rijn', '2402DL', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Eethuis Hoofstraat', 'Eethuis Hoofstraat', 'woo9-9@import.local', NULL, 'Hooftstraat 78', 'Alphen aan den Rijn', '2406 GL', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Ramsis', 'Ramsis', 'woo9-10@import.local', NULL, 'Schoolstraat 30', 'Den Haag', '2511 AX', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bakkerij Bahar Nur', 'Bakkerij Bahar Nur', 'woo9-11@import.local', NULL, 'Dierenselaan 127', 'Den Haag', '2573XS', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('De Serar''s', 'De Serar''s', 'woo9-12@import.local', NULL, 'De Stede 21', 'Den Haag', '2543 BG', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Lekkerland Nederland B.V.', 'Lekkerland Nederland B.V.', 'woo9-13@import.local', NULL, 'Ekkersrijt 7601', 'Son en Breugel', '5692 HR', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('San Marina', 'San Marina', 'woo9-14@import.local', NULL, 'Gerrit Achterberghove', 'Zoetermeer', '2717 XZ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('De Luifelbaan', 'De Luifelbaan', 'woo9-15@import.local', NULL, 'Vijf Meiplein', 'Leiden', '2321 TC', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizza Express', 'Pizza Express', 'woo9-16@import.local', NULL, 'Schoolstraat 103', 'Voorschoten', '2251 BG', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bakkerij Çiçek', 'Bakkerij Çiçek', 'woo9-17@import.local', NULL, 'Middelwaard 62', 'Zoetermeer', '2716 CW', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bakkerij de Hazelaar', 'Bakkerij de Hazelaar', 'woo9-18@import.local', NULL, 'Hazelaarstraat 10', 'Woerden', '3442 EN', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Eethuis Ak-AL', 'Eethuis Ak-AL', 'woo9-19@import.local', NULL, 'Stationsweg 18', 'Leiden', '2312 AV', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Alesta Food', 'Alesta Food', 'woo9-20@import.local', NULL, 'Ambachtsherenpad 12, 2722 BS Zoetermeer', 'Zoetermeer', '2722 BS', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bakkerij Nasib', 'Bakkerij Nasib', 'woo9-21@import.local', NULL, 'Weidstraat 11', 'IJsselstein', '3401 DL', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizza Aro', 'Pizza Aro', 'woo9-22@import.local', NULL, 'Wattstraat 7A', 'Zoetermeer', '2723 PZ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Aps Burger', 'Aps Burger', 'woo9-23@import.local', NULL, 'Bevrijdingsplein 43', 'Leiden', '2321 DX', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Elif Bakkerij', 'Elif Bakkerij', 'woo9-24@import.local', NULL, 'Kentgensplein 13', 'Zoetermeer', '2717 HS', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Ak-Al Bakkerij', 'Ak-Al Bakkerij', 'woo9-25@import.local', NULL, 'Sumatrastraat 155', 'Leiden', '2315 BC', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Sultan Ahmet BV', 'Sultan Ahmet BV', 'woo9-26@import.local', NULL, 'Watermolen 6', 'Leiden', '2317 ST', 'NL', 'Watermolen 6', 'Leiden', '2317 ST', 'NL', TRUE),
('ZAM ZAM XL', 'ZAM ZAM XL', 'woo9-27@import.local', NULL, 'Raamsteeg 73', 'Leiden', '2311 PM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Oranje Oosterheem', 'Oranje Oosterheem', 'woo9-28@import.local', NULL, 'Westerschelde 364', 'Zoetermeer', '2721 NN', 'NL', 'Westerschelde 364', 'Zoetermeer', '2721 NN', 'NL', TRUE),
('Supermarkt Joud', 'Supermarkt Joud', 'woo9-29@import.local', NULL, 'Venneperstraat 12', 'Nieuw-Vennep', '2151 AR', 'NL', 'Venneperstraat 12', 'Nieuw-Vennep', '2151 AR', 'NL', TRUE),
('Dream Kebab Voorhout', 'Dream Kebab Voorhout', 'woo9-30@import.local', NULL, 'Herenstraat 88A', 'Voorhout', '2215KK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Snackbar te britten', 'Snackbar te britten', 'woo9-31@import.local', NULL, 'Zwaaikom 7', 'Katwijk aan Zee', '2225 HX', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Broodjeszaak de Mix', 'Broodjeszaak de Mix', 'woo9-32@import.local', NULL, 'Kostmand 18a', 'Huizen', '1276 CJ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Ekmek Teknesi', 'Ekmek Teknesi', 'woo9-33@import.local', NULL, 'Burgemeester van Leeuwenlaan 77', 'Amsterdam', '1064 KM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('De Rotonde Kebab', 'De Rotonde Kebab', 'woo9-34@import.local', NULL, 'Slotermeerlaan 3', 'Amsterdam', '1064GX', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Dream Kebab Katwijk', 'Dream Kebab Katwijk', 'woo9-35@import.local', NULL, 'Taatedam 2', 'Katwijk aan zee', '2225 BN', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Ak-Al Bakkerij Herenstraat', 'Ak-Al Bakkerij Herenstraat', 'woo9-36@import.local', NULL, 'Herenstraat 4', 'Leiden', '2313 AK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Rania', 'Rania', 'woo9-37@import.local', NULL, 'Winkelhof 5', 'Leiderdorp', '2353 EH', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizzeria Roomburg', 'Pizzeria Roomburg', 'woo9-38@import.local', NULL, 'IJsselkade 43', 'Leiden', '2314VM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizza de lier', 'Pizza de lier', 'woo9-39@import.local', NULL, 'Michiel A. de Ruyterstraat 22', 'De Lier', '2678 GB', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bella Ay Pizza & Döner Huis', 'Bella Ay Pizza & Döner Huis', 'woo9-40@import.local', NULL, 'Dijkstraat 37', 'Honselersdijk', '2675 AV', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Snackbar De Joker Pizzeria Grillroom', 'Snackbar De Joker Pizzeria Grillroom', 'woo9-41@import.local', NULL, 'Bergweg 160-A', 'Rotterdam', '3036 BK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Food Staion', 'Food Staion', 'woo9-42@import.local', NULL, 'Stieltjesweg 232', 'Delft', '2628 CK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Aya hicret', 'Aya hicret', 'woo9-43@import.local', NULL, 'Lange Kerkstraat 35/A', 'Schiedam', '3111 NN', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Nur Bakkerij', 'Nur Bakkerij', 'woo9-44@import.local', NULL, 'Haarlemmerstraat 259', 'Leiden', '2312 DT', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Groen76', 'Groen76', 'woo9-45@import.local', NULL, 'Stevinstraat 159', 'Den Haag', '2587 EE', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Saray PideHuis', 'Saray PideHuis', 'woo9-46@import.local', NULL, 'Steenstraat 20', 'Leiden', '2312 BW', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizza Pizza', 'Pizza Pizza', 'woo9-47@import.local', NULL, 'Erasmusweg 2', 'Den Haag', '2532 CP', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Tasty Corner Delft', 'Tasty Corner Delft', 'woo9-48@import.local', NULL, 'Zuidwal 47', 'Delft', '2611 DD', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('bakkerij Aksu', 'bakkerij Aksu', 'woo9-49@import.local', NULL, 'Wouwermanstraat 3', 'Den Haag', '2525 KM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Aktas Supermarkt & Bakkerij', 'Aktas Supermarkt & Bakkerij', 'woo9-50@import.local', NULL, 'Jan van der Heijdenstraat 115', 'Den Haag', '2522 EM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bakkerij Hesse Place', 'Bakkerij Hesse Place', 'woo9-51@import.local', NULL, 'Hesseplaats 71', 'Rotterdam', '3069EA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Arya Eethuis Leiden', 'Arya Eethuis Leiden', 'woo9-52@import.local', NULL, 'Standerdmolen 19', 'Leiden', '2317 NZ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Sohbet', 'Sohbet', 'woo9-53@import.local', NULL, 'Calandkade 168', 'Den Haag', '2521AA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizza Spidi', 'Pizza Spidi', 'woo9-54@import.local', NULL, 'Van Nesstraat 31', 'Alphen aan den Rijn', '2404 AV', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizzeria La Dolce Vita', 'Pizzeria La Dolce Vita', 'woo9-55@import.local', NULL, 'Rembrandtlaan 52', 'Voorburg', '2271 GK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('EetCafe De haven', 'EetCafe De haven', 'woo9-56@import.local', NULL, 'Calandakade 170', 'Den Haag', '2521AA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Yahya VOF', 'Yahya VOF', 'woo9-57@import.local', NULL, 'Paul Krugerlaan 36 -40', 'Den Haag', '2571 HK', 'NL', 'Paul Krugerlaan 36 -40', 'Den Haag', '2571 HK', 'NL', TRUE),
('EKO Supermarkt', 'EKO Supermarkt', 'woo9-58@import.local', NULL, 'Kempstraat 122', 'Den Haag', '2572 GK', 'NL', 'Kempstraat 122', 'Den Haag', '2572 GK', 'NL', TRUE),
('Slagerij Atas', 'Slagerij Atas', 'woo9-59@import.local', NULL, 'Pr. Irenelaan 96', 'Alphen aan den Rijn', '2404 BJ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('MD Food', 'MD Food', 'woo9-60@import.local', NULL, 'Petuniatuin 8', 'Zoetermeer', '2724 NA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('TokTok Chicken Akdeniz', 'TokTok Chicken Akdeniz', 'woo9-61@import.local', NULL, 'Proostwetering 80b', 'Utrecht', '3543 AJ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Tok Tok Chicken', 'Tok Tok Chicken', 'woo9-62@import.local', NULL, 'Bisonspoor 1150', 'Maarssen', '3605 LS', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Karadag Bakeries', 'Karadag Bakeries', 'woo9-63@import.local', NULL, 'Oosterheemplein 492', 'Zoetermeer', '2721 NJ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Krijgsman Food & Service', 'Krijgsman Food & Service', 'woo9-64@import.local', NULL, 'Pietstuurmanweg 5', 'Waddinxveen', '2742 JX', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Dream Kebab Noordwijkerhout', 'Dream Kebab Noordwijkerhout', 'woo9-65@import.local', NULL, 'Zeestraat 4', 'Noordwijkerhout', '2211 XG', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('The Address Cafe Restaurant', 'The Address Cafe Restaurant', 'woo9-66@import.local', NULL, 'Slotermeerlaan 111', 'Amsterdam', '1063 JN', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Yeni Bahar BV', 'Yeni Bahar BV', 'woo9-67@import.local', NULL, 'Oostermeent noord 56', 'Huizen', '1274SC', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Snackbar Onder Den Toren', 'Snackbar Onder Den Toren', 'woo9-68@import.local', NULL, 'Voorstraat 3', 'Wijk aan Zee', '1949 BG', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Simit Paleis A.S.', 'Simit Paleis A.S.', 'woo9-69@import.local', NULL, 'Postjesweg 105', 'Amsterdam', '1057 DZ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Hoornes Supermarkt en Bakkerij', 'Hoornes Supermarkt en Bakkerij', 'woo9-70@import.local', NULL, 'Hoorneslaan 329', 'Katwijk aan Zee', '2221 GA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Slagerij AsSalaam', 'Slagerij AsSalaam', 'woo9-71@import.local', NULL, 'Dierenselaan 1', 'Den Haag', '2573 KA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('MILJON BV', 'MILJON BV', 'woo9-72@import.local', NULL, 'laan van waalhaven 482', 'Den Haag', '2497GR', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Ons Bakkertje de veen', 'Ons Bakkertje de veen', 'woo9-73@import.local', NULL, 'Noordeinde 13', 'Roelofarendsveen', '2371CM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Massada Roelofarendsveen', 'Massada Roelofarendsveen', 'woo9-74@import.local', NULL, 'Noordplein 3', 'Roelofarendsveen', '2371 DA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Yeyen Supermarkt', 'Yeyen Supermarkt', 'woo9-75@import.local', NULL, 'Escamplaan 305', 'Den Haag', '2547 EA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Durum Evi', 'Durum Evi', 'woo9-76@import.local', NULL, 'Paul Krugerplein 7', 'Den Haag', '2571 HT', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Snackbar Stevenshof', 'Snackbar Stevenshof', 'woo9-77@import.local', NULL, 'Stevensbloem 5', 'Leiden', '2331 JA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Orange Food Group B.V.', 'Orange Food', 'woo9-78@import.local', NULL, 'Doctor Wiardi Beckmansingel 13', 'Vlaardingen', '3132CL', 'NL', 'Doctor Wiardi Beckmansingel 13', 'Vlaardingen', '3132CL', 'NL', TRUE),
('AKK Doner Haarlem', 'AKK Doner Haarlem', 'woo9-79@import.local', NULL, 'Kruisweg 48', 'Haarlem', '2011LD', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Eetcafe Elif', 'Eetcafe Elif', 'woo9-80@import.local', NULL, 'Dedemsvaartweg', 'Den Haag', '2545 AX', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Can Market', 'Can Market', 'woo9-81@import.local', NULL, 'Kon. Wilhelminalaan 68-70', 'Gorinchem', '4205 EZ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Karadag Food', 'Karadag Food', 'woo9-82@import.local', NULL, 'Meeuwenveld 16', 'Zoetermeer', '2727 AK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('AG Emmoglu Supermarkt', 'AG Emmoglu Supermarkt', 'woo9-83@import.local', NULL, 'Brandtstraat 1', 'Den Haag', '2572CA Den Haag', 'NL', 'Brandtstraat 1', 'Den Haag', '2572CA Den Haag', 'NL', TRUE),
('Berat Supermarket', 'Berat Supermarket', 'woo9-84@import.local', NULL, 'Terletstraat 26', 'Den Haag', '2573 EZ', 'NL', 'Terletstraat 26', 'Den Haag', '2573 EZ', 'NL', TRUE),
('Desginverenda', 'Desginverenda', 'woo9-85@import.local', NULL, 'Jacob schorerlaan 41', 'Den haag', '2525ZP', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Supermarkt Houtwijk', 'Supermarkt Houtwijk', 'woo9-86@import.local', NULL, NULL, NULL, NULL, 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Fastfood Ramak', 'Fastfood Ramak', 'woo9-87@import.local', NULL, 'Oude Kustlijn 106', 'Den Haag', '2496 SH', 'NL', NULL, NULL, NULL, 'NL', TRUE);

-- Map by email pattern woo9-*
INSERT INTO woo_migration_map (entity_type, woo_id, new_id)
SELECT 'customer', company_name, id FROM customers WHERE email LIKE 'woo9-%@import.local'
ON CONFLICT (entity_type, woo_id) DO NOTHING;

SELECT (SELECT COUNT(*) FROM woo_migration_map WHERE entity_type = 'customer') as mapped;