-- Batch 10 customers: 94
CREATE TABLE IF NOT EXISTS woo_migration_map (entity_type TEXT NOT NULL, woo_id TEXT NOT NULL, new_id UUID NOT NULL, UNIQUE(entity_type, woo_id));

INSERT INTO customers (company_name, contact_person, email, phone, billing_street, billing_city, billing_postal_code, billing_country, shipping_street, shipping_city, shipping_postal_code, shipping_country, shipping_same_as_billing)
VALUES
('Bakkerij Nasib', 'Bakkerij Nasib', 'woo10-1@import.local', NULL, 'Weidstraat 11', 'IJsselstein', '3401 DL', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bakkerij de Hazelaar', 'Bakkerij de Hazelaar', 'woo10-2@import.local', NULL, 'Hazelaarstraat 10', 'Woerden', '3442 EN', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Saray PideHuis', 'Saray PideHuis', 'woo10-3@import.local', NULL, 'Steenstraat 20', 'Leiden', '2312 BW', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Elif Bakkerij', 'Elif Bakkerij', 'woo10-4@import.local', NULL, 'Kentgensplein 13', 'Zoetermeer', '2717 HS', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Aps Burger', 'Aps Burger', 'woo10-5@import.local', NULL, 'Bevrijdingsplein 43', 'Leiden', '2321 DX', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Ak-Al Bakkerij', 'Ak-Al Bakkerij', 'woo10-6@import.local', NULL, 'Sumatrastraat 155', 'Leiden', '2315 BC', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Oranje Oosterheem', 'Oranje Oosterheem', 'woo10-7@import.local', NULL, 'Westerschelde 364', 'Zoetermeer', '2721 NN', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizza de lier', 'Pizza de lier', 'woo10-8@import.local', NULL, 'Michiel A. de Ruyterstraat 22', 'De Lier', '2678 GB', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Sultan Ahmet BV', 'Sultan Ahmet BV', 'woo10-9@import.local', NULL, 'Watermolen 6', 'Leiden', '2317 ST', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Birlik B.V.', 'Birlik B.V.', 'woo10-10@import.local', NULL, 'Zuiderkruis 179', 'Veenendaal', '3902 WG', 'NL', 'Zuiderkruis 179', 'Veenendaal', '3902 WG', 'NL', TRUE),
('Mirom supermarkt', 'Mirom supermarkt', 'woo10-11@import.local', NULL, 'Spinozaweg 407', 'Rotterdam', '3076 ET', 'NL', 'Spinozaweg 407', 'Rotterdam', '3076 ET', 'NL', TRUE),
('Simit Paleis A.S.', 'Simit Paleis A.S.', 'woo10-12@import.local', NULL, 'Postjesweg 105', 'Amsterdam', '1057 DZ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('The Address Cafe Restaurant', 'The Address Cafe Restaurant', 'woo10-13@import.local', NULL, 'Slotermeerlaan 111', 'Amsterdam', '1063 JN', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Snackbar te britten', 'Snackbar te britten', 'woo10-14@import.local', NULL, 'Zwaaikom 7', 'Katwijk aan Zee', '2225 HX', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Dream Kebab Voorhout', 'Dream Kebab Voorhout', 'woo10-15@import.local', NULL, 'Herenstraat 88A', 'Voorhout', '2215KK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Dream Kebab Katwijk', 'Dream Kebab Katwijk', 'woo10-16@import.local', NULL, 'Taatedam 2', 'Katwijk aan zee', '2225 BN', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Dream Kebab Noordwijkerhout', 'Dream Kebab Noordwijkerhout', 'woo10-17@import.local', NULL, 'Zeestraat 4', 'Noordwijkerhout', '2211 XG', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Broodjeszaak de Mix', 'Broodjeszaak de Mix', 'woo10-18@import.local', NULL, 'Kostmand 18a', 'Huizen', '1276 CJ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('De Rotonde Kebab', 'De Rotonde Kebab', 'woo10-19@import.local', NULL, 'Slotermeerlaan 3', 'Amsterdam', '1064GX', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Ekmek Teknesi', 'Ekmek Teknesi', 'woo10-20@import.local', NULL, 'Burgemeester van Leeuwenlaan 77', 'Amsterdam', '1064 KM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Ak-Al Bakkerij Herenstraat', 'Ak-Al Bakkerij Herenstraat', 'woo10-21@import.local', NULL, 'Herenstraat 4', 'Leiden', '2313 AK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Fastfood Ramak', 'Fastfood Ramak', 'woo10-22@import.local', NULL, 'Oude Kustlijn 106', 'Den Haag', '2496 SH', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('De Serar''s', 'De Serar''s', 'woo10-23@import.local', NULL, 'De Stede 21', 'Den Haag', '2543 BG', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Star Eethuis', 'Star Eethuis', 'woo10-24@import.local', NULL, 'Jaap Hoekdreef 20', 'Den Haag', '2492 JS', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizzeria & Dönerhuis De Gaarde', 'Pizzeria & Dönerhuis De Gaarde', 'woo10-25@import.local', NULL, 'Vrederustlaan 123', 'Den Haag', '2543 SM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Jacks corner', 'Jacks corner', 'woo10-26@import.local', NULL, 'Leemansplein 544', 'Den Haag', '2521 EJ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bella Ay Pizza & Döner Huis', 'Bella Ay Pizza & Döner Huis', 'woo10-27@import.local', NULL, 'Dijkstraat 37', 'Honselersdijk', '2675 AV', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Groen76', 'Groen76', 'woo10-28@import.local', NULL, 'Stevinstraat 159', 'Den Haag', '2587 EE', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Snackbar De Joker Pizzeria Grillroom', 'Snackbar De Joker Pizzeria Grillroom', 'woo10-29@import.local', NULL, 'Bergweg 160-A', 'Rotterdam', '3036 BK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Aya hicret', 'Aya hicret', 'woo10-30@import.local', NULL, 'Lange Kerkstraat 35/A', 'Schiedam', '3111 NN', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizza Pizza', 'Pizza Pizza', 'woo10-31@import.local', NULL, 'Erasmusweg 2', 'Den Haag', '2532 CP', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Seda Bakkerij', 'Seda Bakkerij', 'woo10-32@import.local', NULL, 'Leyweg 1170', 'Den Haag', '2545 HH', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Evin 2 broodjeszaak', 'Evin 2 broodjeszaak', 'woo10-33@import.local', NULL, 'Kempstraat 17', 'Den Haag', '2572 GA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bakkerij Hesse Place', 'Bakkerij Hesse Place', 'woo10-34@import.local', NULL, 'Hesseplaats 71', 'Rotterdam', '3069EA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Suradiya Horeca', 'Suradiya Horeca', 'woo10-35@import.local', NULL, 'Vrouw Avenweg 688', 'Den Haag', '2493 WZ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Eethuis Lage Veld', 'Eethuis Lage Veld', 'woo10-36@import.local', NULL, 'Parijsplein 12', 'Den Haag', '2548 VL', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('ZAM ZAM XL', 'ZAM ZAM XL', 'woo10-37@import.local', NULL, 'Raamsteeg 73', 'Leiden', '2311 PM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Ramsis', 'Ramsis', 'woo10-38@import.local', NULL, 'Schoolstraat 30', 'Den Haag', '2511 AX', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizza Spidi', 'Pizza Spidi', 'woo10-39@import.local', NULL, 'Van Nesstraat 31', 'Alphen aan den Rijn', '2404 AV', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Ons Bakkertje de veen', 'Ons Bakkertje de veen', 'woo10-40@import.local', NULL, 'Noordeinde 13', 'Roelofarendsveen', '2371CM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bakkerij Driebergen', 'Bakkerij Driebergen', 'woo10-41@import.local', NULL, 'Driebergenstraat 337', 'Den Haag', '2546 BK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('HerenHof Eethuis', 'HerenHof Eethuis', 'woo10-42@import.local', NULL, 'HerenHof 287', 'Alpen aan den Rijn', '2402DL', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Eethuis Hoofstraat', 'Eethuis Hoofstraat', 'woo10-43@import.local', NULL, 'Hooftstraat 78', 'Alphen aan den Rijn', '2406 GL', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('EetCafe De haven', 'EetCafe De haven', 'woo10-44@import.local', NULL, 'Calandakade 170', 'Den Haag', '2521AA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Tasty Corner Delft', 'Tasty Corner Delft', 'woo10-45@import.local', NULL, 'Zuidwal 47', 'Delft', '2611 DD', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Yeyen', 'Yeyen', 'woo10-46@import.local', NULL, NULL, 'Den Haag', '2547 EA', 'NL', NULL, 'Den Haag', '2547 EA', 'NL', TRUE),
('San Marina', 'San Marina', 'woo10-47@import.local', NULL, 'Gerrit Achterberghove', 'Zoetermeer', '2717 XZ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Karadag Bakeries', 'Karadag Bakeries', 'woo10-48@import.local', NULL, 'Oosterheemplein 492', 'Zoetermeer', '2721 NJ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizza Express', 'Pizza Express', 'woo10-49@import.local', NULL, 'Schoolstraat 103', 'Voorschoten', '2251 BG', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('De Luifelbaan', 'De Luifelbaan', 'woo10-50@import.local', NULL, 'Vijf Meiplein', 'Leiden', '2321 TC', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bakkerij Çiçek', 'Bakkerij Çiçek', 'woo10-51@import.local', NULL, 'Middelwaard 62', 'Zoetermeer', '2716 CW', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Eethuis Ak-AL', 'Eethuis Ak-AL', 'woo10-52@import.local', NULL, 'Stationsweg 18', 'Leiden', '2312 AV', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Alesta Food', 'Alesta Food', 'woo10-53@import.local', NULL, 'Ambachtsherenpad 12, 2722 BS Zoetermeer', 'Zoetermeer', '2722 BS', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('MD Food', 'MD Food', 'woo10-54@import.local', NULL, 'Petuniatuin 8', 'Zoetermeer', '2724 NA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizza Aro', 'Pizza Aro', 'woo10-55@import.local', NULL, 'Wattstraat 7A', 'Zoetermeer', '2723 PZ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Karadag Food', 'Karadag Food', 'woo10-56@import.local', NULL, 'Meeuwenveld 16', 'Zoetermeer', '2727 AK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Rania', 'Rania', 'woo10-57@import.local', NULL, 'Winkelhof 5', 'Leiderdorp', '2353 EH', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('JINGDONG RETAIL (NETHERLANDS) B.V.', 'JINGDONG RETAIL (NETHERLANDS) B.V.', 'woo10-58@import.local', NULL, 'Da Vincistraat 5', 'Berkel en Rodenrijs', '2652 XE', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('JAF EN SLAGERIJ EN TOKO', 'JAF EN SLAGERIJ EN TOKO', 'woo10-59@import.local', NULL, 'Raadhuisplein 131', 'Krimpen aan den IJssel', '2922AL', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Serdar Supermarkt', 'Serdar Supermarkt', 'woo10-60@import.local', NULL, 'Rijksstraatweg 46', 'Hellevoetsluis', '3223 KA', 'NL', 'Rijksstraatweg 46', 'Hellevoetsluis', '3223 KA', 'NL', TRUE),
('AKK Doner Haarlem', 'AKK Doner Haarlem', 'woo10-61@import.local', NULL, 'Kruisweg 48', 'Haarlem', '2011LD', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Yeni Bahar BV', 'Yeni Bahar BV', 'woo10-62@import.local', NULL, 'Oostermeent noord 56', 'Huizen', '1274SC', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Tasty Point', 'Tasty Point', 'woo10-63@import.local', NULL, 'Voldersgracht 42', 'Den Haag', '2512JV', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Durum Evi', 'Durum Evi', 'woo10-64@import.local', NULL, 'Paul Krugerplein 7', 'Den Haag', '2571 HT', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Eetcafe Elif', 'Eetcafe Elif', 'woo10-65@import.local', NULL, 'Dedemsvaartweg', 'Den Haag', '2545 AX', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Arya Eethuis Leiden', 'Arya Eethuis Leiden', 'woo10-66@import.local', NULL, 'Standerdmolen 19', 'Leiden', '2317 NZ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Supermarkt Buytenwegh', 'Supermarkt Buytenwegh', 'woo10-67@import.local', NULL, 'Titus Brandsmahove 58', 'Zoetermeer.', '2717 TH', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('L.A. American Food', 'L.A. American Food', 'woo10-68@import.local', NULL, 'Gedempte Gracht 405 E', 'Den Haag', '2512AM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Slagerij Atas', 'Slagerij Atas', 'woo10-69@import.local', NULL, 'Pr. Irenelaan 96', 'Alphen aan den Rijn', '2404 BJ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Sohbet', 'Sohbet', 'woo10-70@import.local', NULL, 'Calandkade 168', 'Den Haag', '2521AA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bakkerij Bahar Nur', 'Bakkerij Bahar Nur', 'woo10-71@import.local', NULL, 'Dierenselaan 127', 'Den Haag', '2573XS', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Massada Roelofarendsveen', 'Massada Roelofarendsveen', 'woo10-72@import.local', NULL, 'Noordplein 3', 'Roelofarendsveen', '2371 DA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Berat Supermarket', 'Berat Supermarket', 'woo10-73@import.local', NULL, 'Terletstraat 26', 'Den Haag', '2573 EZ', 'NL', 'Terletstraat 26', 'Den Haag', '2573 EZ', 'NL', TRUE),
('EKO Supermarkt', 'EKO Supermarkt', 'woo10-74@import.local', NULL, 'Kempstraat 122', 'Den Haag', '2572 GK', 'NL', 'Kempstraat 122', 'Den Haag', '2572 GK', 'NL', TRUE),
('Luiten Food', 'Luiten Food', 'woo10-75@import.local', '0031 71 580 8020', 'Klaverblad 11', 'Leidschendam', '2266 JK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('TokTok Chicken Akdeniz', 'TokTok Chicken Akdeniz', 'woo10-76@import.local', NULL, 'Proostwetering 80b', 'Utrecht', '3543 AJ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Tok Tok Chicken', 'Tok Tok Chicken', 'woo10-77@import.local', NULL, 'Bisonspoor 1150', 'Maarssen', '3605 LS', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Delice Supermarket', 'Delice Supermarket', 'woo10-78@import.local', NULL, 'Hornweg 185', 'Aalsmeer', '1432 GH', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Nur Bakkerij', 'Nur Bakkerij', 'woo10-79@import.local', NULL, 'Haarlemmerstraat 259', 'Leiden', '2312 DT', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Sohbet BBQ cafe restaurant', 'Sohbet BBQ cafe restaurant', 'woo10-80@import.local', NULL, 'Middellaan 5', 'Velp', '6288 RP', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('baba de shoarmakoning', 'baba de shoarmakoning', 'woo10-81@import.local', NULL, 'Kuenenplein 3', 'Beverwijk', '1944 RK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Snackbar Onder Den Toren', 'Snackbar Onder Den Toren', 'woo10-82@import.local', NULL, 'Voorstraat 3', 'Wijk aan Zee', '1949 BG', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Fen Döner', 'Fen Döner', 'woo10-83@import.local', NULL, 'Schoolstraat 9a', 'Nieuw-Vennep', '2151 AA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Masters Doner', 'Masters Doner', 'woo10-84@import.local', NULL, 'Kruisweg 985A', 'Hoofddorp', '2132 CE', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Indoor SpeelParadijs ZuiderPark', 'Indoor SpeelParadijs ZuiderPark', 'woo10-85@import.local', NULL, 'Mr. P. Droogleever Fortuynweg 79', 'Den Haag', '2533SP', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizza Bella Maria', 'Pizza Bella Maria', 'woo10-86@import.local', NULL, 'Van Zeggelenlaan 81', 'Den Haag', '2524 AC', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizzeria La Dolce Vita', 'Pizzeria La Dolce Vita', 'woo10-87@import.local', NULL, 'Rembrandtlaan 52', 'Voorburg', '2271 GK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Gulcan Bakkerij', 'Gulcan Bakkerij', 'woo10-88@import.local', NULL, 'Morsweg 23', 'Leiden', '2312 AS', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Can Market', 'Can Market', 'woo10-89@import.local', NULL, 'Kon. Wilhelminalaan 68-70', 'Gorinchem', '4205 EZ', 'NL', 'Kon. Wilhelminalaan 68-70', 'Gorinchem', '4205 EZ', 'NL', TRUE),
('Emigro B.V', 'Emigro B.V', 'woo10-90@import.local', NULL, 'Van der Kunstraat 30/32', 'Den Haag', '2521 BC', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Adam Broodjeszaak', 'Adam Broodjeszaak', 'woo10-91@import.local', NULL, 'Hoefkade 796', 'Den Haag', '2526 CT', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Sultan Pizzeria', 'Sultan Pizzeria', 'woo10-92@import.local', NULL, 'De Markt 325', 'Krimpen aan de Lek', '2931 EC', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Supermarkt Houtwijk', 'Supermarkt Houtwijk', 'woo10-93@import.local', NULL, 'Hildo kroplaan 96', 'Den Haag', '2552 XT', 'NL', 'Hildo kroplaan 96', 'Den Haag', '2552 XT', 'NL', TRUE),
('Yeyen Supermarkt', 'Yeyen Supermarkt', 'woo10-94@import.local', NULL, 'Escamplaan 305', 'Den Haag', '2547 EA', 'NL', 'Escamplaan 305', 'Den Haag', '2547 EA', 'NL', TRUE);

-- Map by email pattern woo10-*
INSERT INTO woo_migration_map (entity_type, woo_id, new_id)
SELECT 'customer', company_name, id FROM customers WHERE email LIKE 'woo10-%@import.local'
ON CONFLICT (entity_type, woo_id) DO NOTHING;

SELECT (SELECT COUNT(*) FROM woo_migration_map WHERE entity_type = 'customer') as mapped;