-- Batch 6 customers: 78
CREATE TABLE IF NOT EXISTS woo_migration_map (entity_type TEXT NOT NULL, woo_id TEXT NOT NULL, new_id UUID NOT NULL, UNIQUE(entity_type, woo_id));

INSERT INTO customers (company_name, contact_person, email, phone, billing_street, billing_city, billing_postal_code, billing_country, shipping_street, shipping_city, shipping_postal_code, shipping_country, shipping_same_as_billing)
VALUES
('Bakkerij Hesse Place', 'Bakkerij Hesse Place', 'woo6-1@import.local', NULL, 'Hesseplaats 71', 'Rotterdam', '3069EA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Eetcafe Elif', 'Eetcafe Elif', 'woo6-2@import.local', NULL, 'Dedemsvaartweg', 'Den Haag', '2545 AX', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizza Pizza', 'Pizza Pizza', 'woo6-3@import.local', NULL, 'Erasmusweg 2', 'Den Haag', '2532 CP', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizzeria La Dolce Vita', 'Pizzeria La Dolce Vita', 'woo6-4@import.local', NULL, 'Rembrandtlaan 52', 'Voorburg', '2271 GK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizzeria & Dönerhuis De Gaarde', 'Pizzeria & Dönerhuis De Gaarde', 'woo6-5@import.local', NULL, 'Vrederustlaan 123', 'Den Haag', '2543 SM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Dream Kebab Voorhout', 'Dream Kebab Voorhout', 'woo6-6@import.local', NULL, 'Herenstraat 88A', 'Voorhout', '2215KK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Rania', 'Rania', 'woo6-7@import.local', NULL, 'Winkelhof 5', 'Leiderdorp', '2353 EH', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Dream Kebab Katwijk', 'Dream Kebab Katwijk', 'woo6-8@import.local', NULL, 'Taatedam 2', 'Katwijk aan zee', '2225 BN', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Dream Kebab Noordwijkerhout', 'Dream Kebab Noordwijkerhout', 'woo6-9@import.local', NULL, 'Zeestraat 4', 'Noordwijkerhout', '2211 XG', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('De Rotonde Kebab', 'De Rotonde Kebab', 'woo6-10@import.local', NULL, 'Slotermeerlaan 3', 'Amsterdam', '1064GX', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Lekker Jammie', 'Lekker Jammie', 'woo6-11@import.local', NULL, 'Hoge Rijndijk 98', 'Leiden', '2313 KM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Saray PideHuis', 'Saray PideHuis', 'woo6-12@import.local', NULL, 'Steenstraat 20', 'Leiden', '2312 BW', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('ZAM ZAM XL', 'ZAM ZAM XL', 'woo6-13@import.local', NULL, 'Raamsteeg 73', 'Leiden', '2311 PM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Ak-Al Bakkerij Herenstraat', 'Ak-Al Bakkerij Herenstraat', 'woo6-14@import.local', NULL, 'Herenstraat 4', 'Leiden', '2313 AK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Jacks corner', 'Jacks corner', 'woo6-15@import.local', NULL, 'Leemansplein 544', 'Den Haag', '2521 EJ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizzeria Roomburg', 'Pizzeria Roomburg', 'woo6-16@import.local', NULL, 'IJsselkade 43', 'Leiden', '2314VM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Seda Bakkerij', 'Seda Bakkerij', 'woo6-17@import.local', NULL, 'Leyweg 1170', 'Den Haag', '2545 HH', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('HerenHof Eethuis', 'HerenHof Eethuis', 'woo6-18@import.local', NULL, 'HerenHof 287', 'Alpen aan den Rijn', '2402DL', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Eethuis Hoofstraat', 'Eethuis Hoofstraat', 'woo6-19@import.local', NULL, 'Hooftstraat 78', 'Alphen aan den Rijn', '2406 GL', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Babas Restaurant', 'Babas Restaurant', 'woo6-20@import.local', NULL, 'Heeswijkplein 18', 'Den Haag', '2531 HC', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('EetCafe De haven', 'EetCafe De haven', 'woo6-21@import.local', NULL, 'Calandakade 170', 'Den Haag', '2521AA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Gunaydin Sulu Yemek Restaurant', 'Gunaydin Sulu Yemek Restaurant', 'woo6-22@import.local', NULL, 'Gedempte Gracht 405', 'Den Haag', '2512 AM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Sohbet', 'Sohbet', 'woo6-23@import.local', NULL, 'Calandkade 168', 'Den Haag', '2521AA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Supermarkt Houtwijk', 'Supermarkt Houtwijk', 'woo6-24@import.local', NULL, 'Hildo kroplaan 96', 'Den Haag', '2552 XT', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Eetsalon Mazens', 'Eetsalon Mazens', 'woo6-25@import.local', NULL, 'Herenstraat 46', 'Leiden', '2313 AL', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('San Marina', 'San Marina', 'woo6-26@import.local', NULL, 'Gerrit Achterberghove', 'Zoetermeer', '2717 XZ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Nur Bakkerij', 'Nur Bakkerij', 'woo6-27@import.local', NULL, 'Haarlemmerstraat 259', 'Leiden', '2312 DT', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('MD Food', 'MD Food', 'woo6-28@import.local', NULL, 'Petuniatuin 8', 'Zoetermeer', '2724 NA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('De Luifelbaan', 'De Luifelbaan', 'woo6-29@import.local', NULL, 'Vijf Meiplein', 'Leiden', '2321 TC', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizza Aro', 'Pizza Aro', 'woo6-30@import.local', NULL, 'Wattstraat 7A', 'Zoetermeer', '2723 PZ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Alesta Food', 'Alesta Food', 'woo6-31@import.local', NULL, 'Ambachtsherenpad 12, 2722 BS Zoetermeer', 'Zoetermeer', '2722 BS', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bakkerij de Hazelaar', 'Bakkerij de Hazelaar', 'woo6-32@import.local', NULL, 'Hazelaarstraat 10', 'Woerden', '3442 EN', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Sultan Ahmet BV', 'Sultan Ahmet BV', 'woo6-33@import.local', NULL, 'Watermolen 6', 'Leiden', '2317 ST', 'NL', 'Watermolen 6', 'Leiden', '2317 ST', 'NL', TRUE),
('Slagerij Atas', 'Slagerij Atas', 'woo6-34@import.local', NULL, 'Pr. Irenelaan 96', 'Alphen aan den Rijn', '2404 BJ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Can Market', 'Can Market', 'woo6-35@import.local', NULL, 'Kon. Wilhelminalaan 68-70', 'Gorinchem', '4205 EZ', 'NL', 'Kon. Wilhelminalaan 68-70', 'Gorinchem', '4205 EZ', 'NL', TRUE),
('Indoor SpeelParadijs ZuiderPark', 'Indoor SpeelParadijs ZuiderPark', 'woo6-36@import.local', NULL, 'Mr. P. Droogleever Fortuynweg 79', 'Den Haag', '2533SP', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('AKK Doner Haarlem', 'AKK Doner Haarlem', 'woo6-37@import.local', NULL, 'Kruisweg 48', 'Haarlem', '2011LD', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Delice Supermarket', 'Delice Supermarket', 'woo6-38@import.local', NULL, 'Hornweg 185', 'Aalsmeer', '1432 GH', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('EKO Supermarkt', 'EKO Supermarkt', 'woo6-39@import.local', NULL, 'Kempstraat 122', 'Den Haag', '2572 GK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Yahya VOF', 'Yahya VOF', 'woo6-40@import.local', NULL, 'Paul Krugerlaan 36 -40', 'Den Haag', '2571 HK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('AG Emmoglu Supermarkt', 'AG Emmoglu Supermarkt', 'woo6-41@import.local', NULL, 'Brandtstraat 1', 'Den Haag', '2572CA Den Haag', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Kral Durum', 'Kral Durum', 'woo6-42@import.local', NULL, 'Paul Krugerlaan 114', 'Den Haag', '2571 HM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bakkerij Bahar Nur', 'Bakkerij Bahar Nur', 'woo6-43@import.local', NULL, 'Dierenselaan 127', 'Den Haag', '2573XS', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Cafetaria Frankie Den Haag', 'Cafetaria Frankie Den Haag', 'woo6-44@import.local', NULL, 'Herman Costerstraat 182', 'Den Haag', '2571 PE', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Sultan Pizzeria', 'Sultan Pizzeria', 'woo6-45@import.local', NULL, 'De Markt 325', 'Krimpen aan de Lek', '2931 EC', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizza Express', 'Pizza Express', 'woo6-46@import.local', NULL, 'Schoolstraat 103', 'Voorschoten', '2251 BG', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Elif Bakkerij', 'Elif Bakkerij', 'woo6-47@import.local', NULL, 'Kentgensplein 13', 'Zoetermeer', '2717 HS', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Ak-Al Bakkerij', 'Ak-Al Bakkerij', 'woo6-48@import.local', NULL, 'Sumatrastraat 155', 'Leiden', '2315 BC', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('ABM RESTYLING', 'ABM RESTYLING', 'woo6-49@import.local', NULL, NULL, NULL, NULL, 'NL', 'Clara Wieckpad 5', 'Leiden', '2324 DV', 'NL', FALSE),
('Hoornes Supermarkt en Bakkerij', 'Hoornes Supermarkt en Bakkerij', 'woo6-50@import.local', NULL, 'Hoorneslaan 329', 'Katwijk aan Zee', '2221 GA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Aktas Supermarkt & Bakkerij', 'Aktas Supermarkt & Bakkerij', 'woo6-51@import.local', NULL, 'Jan van der Heijdenstraat 115', 'Den Haag', '2522 EM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Luiten Food', 'Luiten Food', 'woo6-52@import.local', '0031 71 580 8020', 'Klaverblad 11', 'Leidschendam', '2266 JK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Oranje Oosterheem', 'Oranje Oosterheem', 'woo6-53@import.local', NULL, 'Westerschelde 364', 'Zoetermeer', '2721 NN', 'NL', 'Westerschelde 364', 'Zoetermeer', '2721 NN', 'NL', TRUE),
('Kral Doner', 'Kral Doner', 'woo6-54@import.local', NULL, 'Beijersstraat 2', 'Den haag', '2572 BE', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('alternatief23 B.V', 'alternatief23 B.V', 'woo6-55@import.local', NULL, 'Zuiderkruis 179', 'Veenendaal', '3902WG', 'NL', 'Zuiderkruis 179', 'Veenendaal', '3902WG', 'NL', TRUE),
('Evin 2 broodjeszaak', 'Evin 2 broodjeszaak', 'woo6-56@import.local', NULL, 'Kempstraat 17', 'Den Haag', '2572 GA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Yeyen Supermarkt', 'Yeyen Supermarkt', 'woo6-57@import.local', NULL, 'Escamplaan 305', 'Den Haag', '2547 EA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Happy Doner Food & Drinks', 'Happy Doner Food & Drinks', 'woo6-58@import.local', NULL, 'Zaanweg 81', 'Wormerveer', '1521 DN', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Snackbar Onder Den Toren', 'Snackbar Onder Den Toren', 'woo6-59@import.local', NULL, 'Voorstraat 3', 'Wijk aan Zee', '1949 BG', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('baba de shoarmakoning', 'baba de shoarmakoning', 'woo6-60@import.local', NULL, 'Kuenenplein 3', 'Beverwijk', '1944 RK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Massada Roelofarendsveen', 'Massada Roelofarendsveen', 'woo6-61@import.local', NULL, 'Noordplein 3', 'Roelofarendsveen', '2371 DA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Adam Broodjeszaak', 'Adam Broodjeszaak', 'woo6-62@import.local', NULL, 'Hoefkade 796', 'Den Haag', '2526 CT', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Ramsis', 'Ramsis', 'woo6-63@import.local', NULL, 'Schoolstraat 30', 'Den Haag', '2511 AX', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizza de lier', 'Pizza de lier', 'woo6-64@import.local', NULL, 'Michiel A. de Ruyterstraat 22', 'De Lier', '2678 GB', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bakkerij Çiçek', 'Bakkerij Çiçek', 'woo6-65@import.local', NULL, 'Middelwaard 62', 'Zoetermeer', '2716 CW', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Tasty Corner Delft', 'Tasty Corner Delft', 'woo6-66@import.local', NULL, 'Zuidwal 47', 'Delft', '2611 DD', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Mirom supermarkt', 'Mirom supermarkt', 'woo6-67@import.local', NULL, 'Spinozaweg 407', 'Rotterdam', '3076 ET', 'NL', 'Spinozaweg 407', 'Rotterdam', '3076 ET', 'NL', TRUE),
('Groen76', 'Groen76', 'woo6-68@import.local', NULL, 'Stevinstraat 159', 'Den Haag', '2587 EE', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Tasty Point', 'Tasty Point', 'woo6-69@import.local', NULL, 'Voldersgracht 42', 'Den Haag', '2512JV', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Aksu Pizza, snacks', 'Aksu Pizza, snacks', 'woo6-70@import.local', NULL, 'Hoofdstraat 87', 'De Lier', '2678 CG', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('MD', 'MD', 'woo6-71@import.local', NULL, NULL, 'Zoetermeer', '2724 NA', 'NL', NULL, 'Zoetermeer', '2724 NA', 'NL', TRUE),
('Ekmek Teknesi', 'Ekmek Teknesi', 'woo6-72@import.local', NULL, 'Burgemeester van Leeuwenlaan 77', 'Amsterdam', '1064 KM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Food Staion', 'Food Staion', 'woo6-73@import.local', NULL, 'Stieltjesweg 232', 'Delft', '2628 CK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizza Spidi', 'Pizza Spidi', 'woo6-74@import.local', NULL, 'Van Nesstraat 31', 'Alphen aan den Rijn', '2404 AV', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bakkerij Driebergen', 'Bakkerij Driebergen', 'woo6-75@import.local', NULL, 'Driebergenstraat 337', 'Den Haag', '2546 BK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Snackbar Stevenshof', 'Snackbar Stevenshof', 'woo6-76@import.local', NULL, 'Stevensbloem 5', 'Leiden', '2331 JA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Krijgsman Food & Service', 'Krijgsman Food & Service', 'woo6-77@import.local', NULL, 'Pietstuurmanweg 5', 'Waddinxveen', '2742 JX', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('JINGDONG RETAIL (NETHERLANDS) B.V.', 'JINGDONG RETAIL (NETHERLANDS) B.V.', 'woo6-78@import.local', NULL, 'Da Vincistraat 5', 'Berkel en Rodenrijs', '2652 XE', 'NL', NULL, NULL, NULL, 'NL', TRUE);

-- Map by email pattern woo6-*
INSERT INTO woo_migration_map (entity_type, woo_id, new_id)
SELECT 'customer', company_name, id FROM customers WHERE email LIKE 'woo6-%@import.local'
ON CONFLICT (entity_type, woo_id) DO NOTHING;

SELECT (SELECT COUNT(*) FROM woo_migration_map WHERE entity_type = 'customer') as mapped;