-- Batch 2 customers: 58
CREATE TABLE IF NOT EXISTS woo_migration_map (entity_type TEXT NOT NULL, woo_id TEXT NOT NULL, new_id UUID NOT NULL, UNIQUE(entity_type, woo_id));

INSERT INTO customers (company_name, contact_person, email, phone, billing_street, billing_city, billing_postal_code, billing_country, shipping_street, shipping_city, shipping_postal_code, shipping_country, shipping_same_as_billing)
VALUES
('Orange Food Group B.V.', NULL, 'woo2-1@import.local', NULL, 'Doctor Wiardi Beckmansingel 13', 'Vlaardingen', '3132CL', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('De Rotonde Kebab', 'De Rotonde Kebab', 'woo2-2@import.local', NULL, 'Slotermeerlaan 3', 'Amsterdam', '1064GX', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Saray PideHuis', 'Saray PideHuis', 'woo2-3@import.local', NULL, 'Steenstraat 20', 'Leiden', '2312 BW', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Supermarkt Joud', 'Supermarkt Joud', 'woo2-4@import.local', NULL, 'Venneperstraat 12', 'Nieuw-Vennep', '2151 AR', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Ramses', 'Ramses', 'woo2-5@import.local', NULL, 'Schoolstraat 30', 'Den Haag', '2511 AX', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Dream Kebab Voorhout', 'Dream Kebab Voorhout', 'woo2-6@import.local', NULL, 'Herenstraat 88A', 'Voorhout', '2215KK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Dream Kebab Katwijk', 'Dream Kebab Katwijk', 'woo2-7@import.local', NULL, 'Taatedam 2', 'Katwijk aan zee', '2225 BN', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Dream Kebab Noordwijkerhout', 'Dream Kebab Noordwijkerhout', 'woo2-8@import.local', NULL, 'Zeestraat 4', 'Noordwijkerhout', '2211 XG', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('MD Food', 'MD Food', 'woo2-9@import.local', NULL, 'Petuniatuin 8', 'Zoetermeer', '2724 NA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bakkerij de Hazelaar', 'Bakkerij de Hazelaar', 'woo2-10@import.local', NULL, 'Hazelaarstraat 10', 'Woerden', '3442 EN', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Sohbet barbecue cafe&restaurant', 'Sohbet barbecue cafe&restaurant', 'woo2-11@import.local', NULL, 'Calandkade 168', 'Den Haag', '2521AA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('EetCafe De haven', 'EetCafe De haven', 'woo2-12@import.local', NULL, 'Calandakade 170', 'Den Haag', '2521AA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Oranje Oosterheem', 'Oranje Oosterheem', 'woo2-13@import.local', NULL, 'Westerschelde 364', 'Zoetermeer', '2721 NN', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizza Aro', 'Pizza Aro', 'woo2-14@import.local', NULL, 'Wattstraat 7A', 'Zoetermeer', '2723 PZ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('San Marina', 'San Marina', 'woo2-15@import.local', NULL, 'Gerrit Achterberghove', 'Zoetermeer', '2717 XZ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Salama Doner Pizza', 'Salama Doner Pizza', 'woo2-16@import.local', NULL, 'Stevensbloem 7', 'Leiden', '2331JA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Snackbar Stevenshof', 'Snackbar Stevenshof', 'woo2-17@import.local', NULL, 'Stevensbloem 5', 'Leiden', '2331 JA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Snackbar Onder Den Toren', 'Snackbar Onder Den Toren', 'woo2-18@import.local', NULL, 'Voorstraat 3', 'Wijk aan Zee', '1949 BG', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Hoornes Supermarkt en Bakkerij', 'Hoornes Supermarkt en Bakkerij', 'woo2-19@import.local', NULL, 'Hoorneslaan 329', 'Katwijk aan Zee', '2221 GA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Massada Roelofarendsveen', 'Massada Roelofarendsveen', 'woo2-20@import.local', NULL, 'Noordplein 3', 'Roelofarendsveen', '2371 DA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Sultan Ahmet BV', 'Sultan Ahmet BV', 'woo2-21@import.local', NULL, 'Watermolen 6', 'Leiden', '2317 ST', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Baronie Doner Place', 'Baronie Doner Place', 'woo2-22@import.local', NULL, 'Baronie 100', 'Alphen aan den Rijn', '2404 XH', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Jacks corner', 'Jacks corner', 'woo2-23@import.local', NULL, 'Leemansplein 544', 'Den Haag', '2521 EJ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Dicle', 'Dicle', 'woo2-24@import.local', NULL, 'Kempstraat 17', 'Den Haag', '2572 GA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('ZAM ZAM XL', 'ZAM ZAM XL', 'woo2-25@import.local', NULL, 'Raamsteeg 73', 'Leiden', '2311 PM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Alesta Food', 'Alesta Food', 'woo2-26@import.local', NULL, 'Ambachtsherenpad 12, 2722 BS Zoetermeer', 'Zoetermeer', '2722 BS', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Ak-Al Bakkerij Herenstraat', 'Ak-Al Bakkerij Herenstraat', 'woo2-27@import.local', NULL, 'Herenstraat 4', 'Leiden', '2313 AK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bakkerij Hesse Place', 'Bakkerij Hesse Place', 'woo2-28@import.local', NULL, 'Hesseplaats 71', 'Rotterdam', '3069EA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizzeria & Dönerhuis De Gaarde', 'Pizzeria & Dönerhuis De Gaarde', 'woo2-29@import.local', NULL, 'Vrederustlaan 123', 'Den Haag', '2543 SM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Seryana', 'Seryana', 'woo2-30@import.local', NULL, 'Hoogstraat 3', 'Gouda', '2801 HG', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Ak-Al', 'Ak-Al', 'woo2-31@import.local', NULL, 'Hooftstraat 78', 'Alphen aan den Rijn', '2406 GL', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Rania', 'Rania', 'woo2-32@import.local', NULL, 'Winkelhof 5', 'Leiderdorp', '2353 EH', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Durum Evi', 'Durum Evi', 'woo2-33@import.local', NULL, 'Paul Krugerplein 7', 'Den Haag', '2571 HT', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Lekker Jammie', 'Lekker Jammie', 'woo2-34@import.local', NULL, 'Hoge Rijndijk 98', 'Leiden', '2313 KM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Yahya VOF', 'Yahya VOF', 'woo2-35@import.local', NULL, 'Paul Krugerlaan 36 -40', 'Den Haag', '2571 HK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('EKO Supermarkt', 'EKO Supermarkt', 'woo2-36@import.local', NULL, 'Kempstraat 122', 'Den Haag', '2572 GK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('De Luifelbaan', 'De Luifelbaan', 'woo2-37@import.local', NULL, 'Vijf Meiplein', 'Leiden', '2321 TC', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Eetcafe Elif', 'Eetcafe Elif', 'woo2-38@import.local', NULL, 'Dedemsvaartweg', 'Den Haag', '2545 AX', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizzeria & Grillroom Hawaii Naaldwijk', 'Pizzeria & Grillroom Hawaii Naaldwijk', 'woo2-39@import.local', NULL, 'Pr. Julianastraat 22', 'Naaldwijk', '2671EK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Serdar Supermarkt', 'Serdar Supermarkt', 'woo2-40@import.local', NULL, 'Rijksstraatweg 46', 'Hellevoetsluis', '3223 KA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Can Market', 'Can Market', 'woo2-41@import.local', NULL, 'Kon. Wilhelminalaan 68-70', 'Gorinchem', '4205 EZ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizza Express', 'Pizza Express', 'woo2-42@import.local', NULL, 'Schoolstraat 103', 'Voorschoten', '2251 BG', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Supermarkt Houtwijk', 'Supermarkt Houtwijk', 'woo2-43@import.local', NULL, 'Hildo kroplaan 96', 'Den Haag', '2552 XT', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Ak-AL Eethuis', 'Ak-AL Eethuis', 'woo2-44@import.local', NULL, 'HerenHof 287', 'Alpen aan den Rijn', '2402DL', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Slagerij Atas', 'Slagerij Atas', 'woo2-45@import.local', NULL, 'Pr. Irenelaan 96', 'Alphen aan den Rijn', '2404 BJ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('De Serar''s', 'De Serar''s', 'woo2-46@import.local', NULL, 'De Stede 21', 'Den Haag', '2543 BG', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Indoor SpeelParadijs ZuiderPark', 'Indoor SpeelParadijs ZuiderPark', 'woo2-47@import.local', NULL, 'Mr. P. Droogleever Fortuynweg 79', 'Den Haag', '2533SP', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Ramsis', 'Ramsis', 'woo2-48@import.local', NULL, 'Schoolstraat 30', 'Den Haag', '2511 AX', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Baran Broodjeszaak', 'Baran Broodjeszaak', 'woo2-49@import.local', NULL, 'Hoefkade 1244', 'Den Haag', '2525 HK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizzeria Roomburg', 'Pizzeria Roomburg', 'woo2-50@import.local', NULL, 'IJsselkade 43', 'Leiden', '2314VM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('baba de shoarmakoning', 'baba de shoarmakoning', 'woo2-51@import.local', NULL, 'Kuenenplein 3', 'Beverwijk', '1944 RK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Birlik B.V.', 'Birlik B.V.', 'woo2-52@import.local', NULL, 'Zuiderkruis 179', 'Veenendaal', '3902 WG', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('HerenHofEethuis', 'HerenHofEethuis', 'woo2-53@import.local', NULL, 'HerenHof 287', 'Alpen aan den Rijn', '2402DL', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Eethuis Hoofstraat', 'Eethuis Hoofstraat', 'woo2-54@import.local', NULL, 'Hooftstraat 78', 'Alphen aan den Rijn', '2406 GL', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('JINGDONG RETAIL (NETHERLANDS) B.V.', 'JINGDONG RETAIL (NETHERLANDS) B.V.', 'woo2-55@import.local', NULL, 'Da Vincistraat 5', 'Berkel en Rodenrijs', '2652 XE', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('De Gouden Wok Zuiderpark', 'De Gouden Wok Zuiderpark', 'woo2-56@import.local', NULL, 'Meester P. Droogleever Fortuynweg 69', 'Den Haag', '2533 SP', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Yeyen Supermarkt', 'Yeyen Supermarkt', 'woo2-57@import.local', NULL, 'Escamplaan 305', 'Den Haag', '2547 EA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Buurtwinkel Stipt', 'Buurtwinkel Stipt', 'woo2-58@import.local', NULL, 'Van Zeggelenlaan 240', 'Den Haag', '2524AZ', 'NL', NULL, NULL, NULL, 'NL', TRUE);

-- Map by email pattern woo2-*
INSERT INTO woo_migration_map (entity_type, woo_id, new_id)
SELECT 'customer', company_name, id FROM customers WHERE email LIKE 'woo2-%@import.local'
ON CONFLICT (entity_type, woo_id) DO NOTHING;

SELECT (SELECT COUNT(*) FROM woo_migration_map WHERE entity_type = 'customer') as mapped;