-- Batch 14 customers: 89
CREATE TABLE IF NOT EXISTS woo_migration_map (entity_type TEXT NOT NULL, woo_id TEXT NOT NULL, new_id UUID NOT NULL, UNIQUE(entity_type, woo_id));

INSERT INTO customers (company_name, contact_person, email, phone, billing_street, billing_city, billing_postal_code, billing_country, shipping_street, shipping_city, shipping_postal_code, shipping_country, shipping_same_as_billing)
VALUES
('Simit Paleis A.S.', 'Simit Paleis A.S.', 'woo14-1@import.local', NULL, 'Postjesweg 105', 'Amsterdam', '1057 DZ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Snackbar te britten', 'Snackbar te britten', 'woo14-2@import.local', NULL, 'Zwaaikom 7', 'Katwijk aan Zee', '2225 HX', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('De Rotonde Kebab', 'De Rotonde Kebab', 'woo14-3@import.local', NULL, 'Slotermeerlaan 3', 'Amsterdam', '1064GX', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Yeni Bahar BV', 'Yeni Bahar BV', 'woo14-4@import.local', NULL, 'Oostermeent noord 56', 'Huizen', '1274SC', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Broodjeszaak de Mix', 'Broodjeszaak de Mix', 'woo14-5@import.local', NULL, 'Kostmand 18a', 'Huizen', '1276 CJ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Dream Kebab Katwijk', 'Dream Kebab Katwijk', 'woo14-6@import.local', NULL, 'Taatedam 2', 'Katwijk aan zee', '2225 BN', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Dream Kebab Noordwijkerhout', 'Dream Kebab Noordwijkerhout', 'woo14-7@import.local', NULL, 'Zeestraat 4', 'Noordwijkerhout', '2211 XG', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Ekmek Teknesi', 'Ekmek Teknesi', 'woo14-8@import.local', NULL, 'Burgemeester van Leeuwenlaan 77', 'Amsterdam', '1064 KM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Dream Kebab Voorhout', 'Dream Kebab Voorhout', 'woo14-9@import.local', NULL, 'Herenstraat 88A', 'Voorhout', '2215KK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('The Address Cafe Restaurant', 'The Address Cafe Restaurant', 'woo14-10@import.local', NULL, 'Slotermeerlaan 111', 'Amsterdam', '1063 JN', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Rania', 'Rania', 'woo14-11@import.local', NULL, 'Winkelhof 5', 'Leiderdorp', '2353 EH', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Seda Bakkerij', 'Seda Bakkerij', 'woo14-12@import.local', NULL, 'Leyweg 1170', 'Den Haag', '2545 HH', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Eetcafe Elif', 'Eetcafe Elif', 'woo14-13@import.local', NULL, 'Dedemsvaartweg', 'Den Haag', '2545 AX', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bakkerij Hesse Place', 'Bakkerij Hesse Place', 'woo14-14@import.local', NULL, 'Hesseplaats 71', 'Rotterdam', '3069EA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizzeria & Dönerhuis De Gaarde', 'Pizzeria & Dönerhuis De Gaarde', 'woo14-15@import.local', NULL, 'Vrederustlaan 123', 'Den Haag', '2543 SM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Nur Bakkerij', 'Nur Bakkerij', 'woo14-16@import.local', NULL, 'Haarlemmerstraat 259', 'Leiden', '2312 DT', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bella Ay Pizza & Döner Huis', 'Bella Ay Pizza & Döner Huis', 'woo14-17@import.local', NULL, 'Dijkstraat 37', 'Honselersdijk', '2675 AV', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Snackbar De Joker Pizzeria Grillroom', 'Snackbar De Joker Pizzeria Grillroom', 'woo14-18@import.local', NULL, 'Bergweg 160-A', 'Rotterdam', '3036 BK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizza Pizza', 'Pizza Pizza', 'woo14-19@import.local', NULL, 'Erasmusweg 2', 'Den Haag', '2532 CP', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Gulcan Bakkerij', 'Gulcan Bakkerij', 'woo14-20@import.local', NULL, 'Morsweg 23', 'Leiden', '2312 AS', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Indoor SpeelParadijs ZuiderPark', 'Indoor SpeelParadijs ZuiderPark', 'woo14-21@import.local', NULL, 'Mr. P. Droogleever Fortuynweg 79', 'Den Haag', '2533SP', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Ak-Al Bakkerij', 'Ak-Al Bakkerij', 'woo14-22@import.local', NULL, 'Sumatrastraat 155', 'Leiden', '2315 BC', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Jacks corner', 'Jacks corner', 'woo14-23@import.local', NULL, 'Leemansplein 544', 'Den Haag', '2521 EJ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Tasty Corner Delft', 'Tasty Corner Delft', 'woo14-24@import.local', NULL, 'Zuidwal 47', 'Delft', '2611 DD', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Ramsis', 'Ramsis', 'woo14-25@import.local', NULL, 'Schoolstraat 30', 'Den Haag', '2511 AX', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Saray PideHuis', 'Saray PideHuis', 'woo14-26@import.local', NULL, 'Steenstraat 20', 'Leiden', '2312 BW', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Durum Evi', 'Durum Evi', 'woo14-27@import.local', NULL, 'Paul Krugerplein 7', 'Den Haag', '2571 HT', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Fastfood Ramak', 'Fastfood Ramak', 'woo14-28@import.local', NULL, 'Oude Kustlijn 106', 'Den Haag', '2496 SH', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Delice Supermarket', 'Delice Supermarket', 'woo14-29@import.local', NULL, 'Hornweg 185', 'Aalsmeer', '1432 GH', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bakkerij Nasib', 'Bakkerij Nasib', 'woo14-30@import.local', NULL, 'Weidstraat 11', 'IJsselstein', '3401 DL', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Eethuis Hoofstraat', 'Eethuis Hoofstraat', 'woo14-31@import.local', NULL, 'Hooftstraat 78', 'Alphen aan den Rijn', '2406 GL', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('HerenHof Eethuis', 'HerenHof Eethuis', 'woo14-32@import.local', NULL, 'HerenHof 287', 'Alpen aan den Rijn', '2402DL', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Sohbet', 'Sohbet', 'woo14-33@import.local', NULL, 'Calandkade 168', 'Den Haag', '2521AA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Sohbet BBQ cafe restaurant', 'Sohbet BBQ cafe restaurant', 'woo14-34@import.local', NULL, 'Middellaan 5', 'Velp', '6288 RP', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Groen76', 'Groen76', 'woo14-35@import.local', NULL, 'Stevinstraat 159', 'Den Haag', '2587 EE', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bakkerij Driebergen', 'Bakkerij Driebergen', 'woo14-36@import.local', NULL, 'Driebergenstraat 337', 'Den Haag', '2546 BK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Emigro B.V', 'Emigro B.V', 'woo14-37@import.local', NULL, 'Van der Kunstraat 30/32', 'Den Haag', '2521 BC', 'NL', 'Van der Kunstraat 30/32', 'Den Haag', '2521 BC', 'NL', TRUE),
('Pizza Spidi', 'Pizza Spidi', 'woo14-38@import.local', NULL, 'Van Nesstraat 31', 'Alphen aan den Rijn', '2404 AV', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Baronie Doner Place', 'Baronie Doner Place', 'woo14-39@import.local', NULL, 'Baronie 100', 'Alphen aan den Rijn', '2404 XH', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Adam Broodjeszaak', 'Adam Broodjeszaak', 'woo14-40@import.local', NULL, 'Hoefkade 796', 'Den Haag', '2526 CT', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('EetCafe De haven', 'EetCafe De haven', 'woo14-41@import.local', NULL, 'Calandakade 170', 'Den Haag', '2521AA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bakkerij Bahar Nur', 'Bakkerij Bahar Nur', 'woo14-42@import.local', NULL, 'Dierenselaan 127', 'Den Haag', '2573XS', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Oranje Snacks', 'Oranje Snacks', 'woo14-43@import.local', NULL, 'Theresiastraat 34', 'Den Haag', '2593 AP', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Supermarkt Houtwijk', 'Supermarkt Houtwijk', 'woo14-44@import.local', NULL, NULL, 'Den Haag', '2552 XT', 'NL', NULL, 'Den Haag', '2552 XT', 'NL', TRUE),
('Yahya VOF', 'Yahya VOF', 'woo14-45@import.local', NULL, 'Paul Krugerlaan 36 -40', 'Den Haag', '2571 HK', 'NL', 'Paul Krugerlaan 36 -40', 'Den Haag', '2571 HK', 'NL', TRUE),
('AG Emmoglu Supermarkt', 'AG Emmoglu Supermarkt', 'woo14-46@import.local', NULL, 'Brandtstraat 1', 'Den Haag', '2572CA Den Haag', 'NL', 'Brandtstraat 1', 'Den Haag', '2572CA Den Haag', 'NL', TRUE),
('EKO Supermarkt', 'EKO Supermarkt', 'woo14-47@import.local', NULL, NULL, 'Den Haag', '2572 GK', 'NL', NULL, 'Den Haag', '2572 GK', 'NL', TRUE),
('Luiten Food', 'Luiten Food', 'woo14-48@import.local', '0031 71 580 8020', 'Klaverblad 11', 'Leidschendam', '2266 JK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('De Luifelbaan', 'De Luifelbaan', 'woo14-49@import.local', NULL, 'Vijf Meiplein', 'Leiden', '2321 TC', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('San Marina', 'San Marina', 'woo14-50@import.local', NULL, 'Gerrit Achterberghove', 'Zoetermeer', '2717 XZ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bakkerij Çiçek', 'Bakkerij Çiçek', 'woo14-51@import.local', NULL, 'Middelwaard 62', 'Zoetermeer', '2716 CW', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Arya Eethuis Leiden', 'Arya Eethuis Leiden', 'woo14-52@import.local', NULL, 'Standerdmolen 19', 'Leiden', '2317 NZ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Alesta Food', 'Alesta Food', 'woo14-53@import.local', NULL, 'Ambachtsherenpad 12, 2722 BS Zoetermeer', 'Zoetermeer', '2722 BS', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Karadag Bakeries', 'Karadag Bakeries', 'woo14-54@import.local', NULL, 'Oosterheemplein 492', 'Zoetermeer', '2721 NJ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bakkerij de Hazelaar', 'Bakkerij de Hazelaar', 'woo14-55@import.local', NULL, 'Hazelaarstraat 10', 'Woerden', '3442 EN', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizza Aro', 'Pizza Aro', 'woo14-56@import.local', NULL, 'Wattstraat 7A', 'Zoetermeer', '2723 PZ', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Aps Burger', 'Aps Burger', 'woo14-57@import.local', NULL, 'Bevrijdingsplein 43', 'Leiden', '2321 DX', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Elif Bakkerij', 'Elif Bakkerij', 'woo14-58@import.local', NULL, 'Kentgensplein 13', 'Zoetermeer', '2717 HS', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Eethuis Ak-AL', 'Eethuis Ak-AL', 'woo14-59@import.local', NULL, 'Stationsweg 18', 'Leiden', '2312 AV', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Meze Food', 'Meze Food', 'woo14-60@import.local', NULL, 'Rue de la gaite 105', 'Anderlecht', '1070', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('ZAM ZAM XL', 'ZAM ZAM XL', 'woo14-61@import.local', NULL, 'Raamsteeg 73', 'Leiden', '2311 PM', 'NL', 'Raamsteeg 73', 'Leiden', '2311 PM', 'NL', TRUE),
('Sultan Ahmet BV', 'Sultan Ahmet BV', 'woo14-62@import.local', NULL, 'Watermolen 6', 'Leiden', '2317 ST', 'NL', 'Watermolen 6', 'Leiden', '2317 ST', 'NL', TRUE),
('De Serar''s', 'De Serar''s', 'woo14-63@import.local', NULL, 'De Stede 21', 'Den Haag', '2543 BG', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('JAF EN SLAGERIJ EN TOKO', 'JAF EN SLAGERIJ EN TOKO', 'woo14-64@import.local', NULL, 'Raadhuisplein 131', 'Krimpen aan den IJssel', '2922AL', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Snackbar Onder Den Toren', 'Snackbar Onder Den Toren', 'woo14-65@import.local', NULL, 'Voorstraat 3', 'Wijk aan Zee', '1949 BG', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Ak-Al Bakkerij Herenstraat', 'Ak-Al Bakkerij Herenstraat', 'woo14-66@import.local', NULL, 'Herenstraat 4', 'Leiden', '2313 AK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Aya hicret', 'Aya hicret', 'woo14-67@import.local', NULL, 'Lange Kerkstraat 35/A', 'Schiedam', '3111 NN', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizzeria La Dolce Vita', 'Pizzeria La Dolce Vita', 'woo14-68@import.local', NULL, 'Rembrandtlaan 52', 'Voorburg', '2271 GK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Pizza Bella Maria', 'Pizza Bella Maria', 'woo14-69@import.local', NULL, 'Van Zeggelenlaan 81', 'Den Haag', '2524 AC', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Tasty Point', 'Tasty Point', 'woo14-70@import.local', NULL, 'Voldersgracht 42', 'Den Haag', '2512JV', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Ons Bakkertje de veen', 'Ons Bakkertje de veen', 'woo14-71@import.local', NULL, 'Noordeinde 13', 'Roelofarendsveen', '2371CM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Yeyen', 'Yeyen', 'woo14-72@import.local', NULL, NULL, 'Den Haag', '2547 EA', 'NL', NULL, 'Den Haag', '2547 EA', 'NL', TRUE),
('Pizza Express', 'Pizza Express', 'woo14-73@import.local', NULL, 'Schoolstraat 103', 'Voorschoten', '2251 BG', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Karadag Food', 'Karadag Food', 'woo14-74@import.local', NULL, 'Meeuwenveld 16', 'Zoetermeer', '2727 AK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Oranje Oosterheem', 'Oranje Oosterheem', 'woo14-75@import.local', NULL, 'Westerschelde 364', 'Zoetermeer', '2721 NN', 'NL', 'Westerschelde 364', 'Zoetermeer', '2721 NN', 'NL', TRUE),
('01Grill', '01Grill', 'woo14-76@import.local', NULL, 'Henri Dunantlaan 82', 'Rijswijk', '2286 GE', 'NL', 'Henri Dunantlaan 82', 'Rijswijk', '2286 GE', 'NL', TRUE),
('Snackbar Frankys', 'Snackbar Frankys', 'woo14-77@import.local', NULL, 'Groenlandselaan 23', 'Delft', '2612JL', 'NL', 'Groenlandselaan 23', 'Delft', '2612JL', 'NL', TRUE),
('Birlik B.V.', 'Birlik B.V.', 'woo14-78@import.local', NULL, 'Zuiderkruis 179', 'Veenendaal', '3902 WG', 'NL', 'Zuiderkruis 179', 'Veenendaal', '3902 WG', 'NL', TRUE),
('AKK Doner Haarlem', 'AKK Doner Haarlem', 'woo14-79@import.local', NULL, 'Kruisweg 48', 'Haarlem', '2011LD', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Slagerij Atas', 'Slagerij Atas', 'woo14-80@import.local', NULL, 'Pr. Irenelaan 96', 'Alphen aan den Rijn', '2404 BJ', 'NL', 'Pr. Irenelaan 96', 'Alphen aan den Rijn', '2404 BJ', 'NL', TRUE),
('Seryana', 'Seryana', 'woo14-81@import.local', NULL, 'Hoogstraat 3', 'Gouda', '2801 HG', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Lekkerland Nederland B.V.', 'Lekkerland Nederland B.V.', 'woo14-82@import.local', NULL, 'Ekkersrijt 7601', 'Son en Breugel', '5692 HR', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('La Casa Doner', 'La Casa Doner', 'woo14-83@import.local', NULL, 'Weimarstraat 343', 'Den Haag', '2562 HK', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Hoornes Supermarkt en Bakkerij', 'Hoornes Supermarkt en Bakkerij', 'woo14-84@import.local', NULL, 'Hoorneslaan 329', 'Katwijk aan Zee', '2221 GA', 'NL', 'Hoorneslaan 329', 'Katwijk aan Zee', '2221 GA', 'NL', TRUE),
('MINI MARKET LUDOGORETS', 'MINI MARKET LUDOGORETS', 'woo14-85@import.local', NULL, 'Fischerstraat 88', 'Den Haag', '2572 RE', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Massada Roelofarendsveen', 'Massada Roelofarendsveen', 'woo14-86@import.local', NULL, 'Noordplein 3', 'Roelofarendsveen', '2371 DA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Snackbar Stevenshof', 'Snackbar Stevenshof', 'woo14-87@import.local', NULL, 'Stevensbloem 5', 'Leiden', '2331 JA', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Gunaydin Sulu Yemek Restaurant', 'Gunaydin Sulu Yemek Restaurant', 'woo14-88@import.local', NULL, 'Gedempte Gracht 405', 'Den Haag', '2512 AM', 'NL', NULL, NULL, NULL, 'NL', TRUE),
('Bakkerij De Kampioen', 'Bakkerij De Kampioen', 'woo14-89@import.local', NULL, 'Loosduinse Hoofdplein 222', 'Den Haag', '2553 CR', 'NL', NULL, NULL, NULL, 'NL', TRUE);

-- Map by email pattern woo14-*
INSERT INTO woo_migration_map (entity_type, woo_id, new_id)
SELECT 'customer', company_name, id FROM customers WHERE email LIKE 'woo14-%@import.local'
ON CONFLICT (entity_type, woo_id) DO NOTHING;

SELECT (SELECT COUNT(*) FROM woo_migration_map WHERE entity_type = 'customer') as mapped;