// ESLint 9 flat config.
//
// `npm run lint` had been dead for some time: ESLint 9 is installed, but no
// config file of either format existed, so every run exited 2 with "couldn't
// find an eslint.config.js" — which reads like a broken toolchain rather than a
// clean run, so nobody noticed the linter had stopped saying anything.
//
// Deliberately close to the Vite react-ts template rather than a stricter
// preset: the point is to get the linter running again on a large existing
// codebase, not to reformat it. Type-aware rules (projectService) are NOT
// enabled — they roughly triple lint time and `tsc --noEmit` in `npm run build`
// already covers what they would catch here.

import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tsPlugin from '@typescript-eslint/eslint-plugin'
import tsParser from '@typescript-eslint/parser'

export default [
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      // Generated by scripts/build-api.mjs from api-src/ — lint the source, not
      // the esbuild bundle.
      'api/*.mjs',
      'scripts/wc-reconcile/**',
      'scripts/create-test-data.js',
    ],
  },

  // Browser app code.
  {
    files: ['src/**/*.{ts,tsx}', 'api-src/**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: globals.browser,
      parser: tsParser,
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...js.configs.recommended.rules,
      ...tsPlugin.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,

      // TS handles undefined identifiers, and no-undef misreads TS type-only
      // globals in .ts files.
      'no-undef': 'off',
      // The TS-aware version understands enums, overloads and declaration merging.
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'none' },
      ],
      // Fast-refresh only preserves state when a module exports components alone.
      // Warn, not error: several files intentionally co-export a type or constant.
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
    },
  },

  // Node scripts: different globals, no React.
  {
    files: ['scripts/**/*.{js,mjs}', '*.config.{js,ts}', 'vite.config.ts'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: globals.node,
      parser: tsParser,
    },
    plugins: { '@typescript-eslint': tsPlugin },
    rules: {
      ...js.configs.recommended.rules,
      'no-undef': 'off',
      'no-unused-vars': 'off',
    },
  },
]
